-- ============================================================================
-- RUTA — MODELO DE DATOS ORACLE
-- ============================================================================
-- Plataforma multi-tenant para administración de operaciones comerciales
-- entre Clientes y Compradores.
--
-- Versión: 1.0
-- Schema/User: RUTA
-- Base: Oracle 12c+
--
-- Este archivo es la traducción del modelo PostgreSQL (ruta_postgres.sql)
-- a sintaxis Oracle, optimizada para importar en Oracle SQL Developer
-- Data Modeler y generar el DER.
--
-- Diferencias respecto a la versión PostgreSQL:
--   - BIGINT          → NUMBER(19)
--   - TEXT            → VARCHAR2(N) o CLOB
--   - TIMESTAMPTZ     → TIMESTAMP WITH TIME ZONE
--   - JSONB           → CLOB (con CHECK IS JSON donde aplica)
--   - BOOLEAN         → CHAR(1) con CHECK ('Y','N')
--   - INET            → VARCHAR2(45)
--   - TEXT[]          → VARCHAR2(N) (serializado por la aplicación)
--   - Particionamiento, RLS, stored procedures y triggers complejos
--     están en la versión PostgreSQL; aquí solo se incluye lo necesario
--     para que el DER refleje la estructura completa.
-- ============================================================================


-- ============================================================================
-- SECCIÓN 1. SCHEMA Y TABLESPACE (referencia)
-- ============================================================================
-- Ejecutar como DBA si se desea crear el usuario/schema:
--
-- CREATE TABLESPACE ruta_data DATAFILE 'ruta_data01.dbf' SIZE 500M AUTOEXTEND ON;
-- CREATE USER ruta IDENTIFIED BY <password>
--   DEFAULT TABLESPACE ruta_data
--   QUOTA UNLIMITED ON ruta_data;
-- GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO ruta;
--
-- Las tablas a continuación asumen que el usuario actual es RUTA.


-- ============================================================================
-- SECCIÓN 2. TABLA: clients
-- ============================================================================

CREATE TABLE clients (
  id                              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_code                   VARCHAR2(100) NOT NULL,
  slug                            VARCHAR2(200) NOT NULL,
  name                            VARCHAR2(500) NOT NULL,
  description                     VARCHAR2(2000),
  contact_person_name             VARCHAR2(300),
  contact_person_document_type    VARCHAR2(50),
  contact_person_document_number  VARCHAR2(100),
  contact_person_phone            VARCHAR2(50),
  contact_person_email            VARCHAR2(300),
  logo_url                        VARCHAR2(2000),
  client_type                     VARCHAR2(20) NOT NULL,
  frontend_mode                   VARCHAR2(40),
  status                          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at                      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT uk_clients_business_code UNIQUE (business_code),
  CONSTRAINT uk_clients_slug UNIQUE (slug),
  CONSTRAINT chk_clients_type CHECK (client_type IN ('API', 'FULL')),
  CONSTRAINT chk_clients_frontend_mode CHECK (
    frontend_mode IS NULL OR frontend_mode IN ('NATIVE_RUTA', 'CUSTOM_LANDING_BY_RUTA')
  ),
  CONSTRAINT chk_clients_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT chk_clients_frontend_type CHECK (
    (client_type = 'API' AND frontend_mode IS NULL) OR
    (client_type = 'FULL' AND frontend_mode IS NOT NULL)
  )
);

COMMENT ON TABLE clients IS 'Tenants de la plataforma. client_id=0 es el cliente plataforma (ADMIN_RUTA).';


-- ============================================================================
-- SECCIÓN 3. TABLA: users
-- ============================================================================

CREATE TABLE users (
  id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                NUMBER(19) NOT NULL,
  user_type                VARCHAR2(30) NOT NULL,
  email                    VARCHAR2(300) NOT NULL,
  password_hash            VARCHAR2(500),
  auth_mode                VARCHAR2(30) DEFAULT 'PASSWORD' NOT NULL,
  external_buyer_id        VARCHAR2(200),
  full_name                VARCHAR2(300),
  document_type            VARCHAR2(50),
  document_number          VARCHAR2(100),
  phone                    VARCHAR2(50),
  status                   VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  last_login_at            TIMESTAMP WITH TIME ZONE,
  password_changed_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_users PRIMARY KEY (id, client_id),
  CONSTRAINT uk_users_client_email UNIQUE (client_id, email),
  CONSTRAINT uk_users_client_external UNIQUE (client_id, external_buyer_id),
  CONSTRAINT fk_users_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT chk_users_type CHECK (
    user_type IN ('ADMIN_RUTA', 'ADMIN_CLIENT', 'OPERATOR_CLIENT', 'BUYER', 'COURIER')
  ),
  CONSTRAINT chk_users_auth_mode CHECK (auth_mode IN ('PASSWORD', 'EXTERNAL_REFERENCE')),
  CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
  CONSTRAINT chk_users_password_consistency CHECK (
    (auth_mode = 'PASSWORD' AND password_hash IS NOT NULL) OR
    (auth_mode = 'EXTERNAL_REFERENCE' AND password_hash IS NULL)
  )
);


-- ============================================================================
-- SECCIÓN 4. TABLAS: buyer_profiles y courier_profiles
-- ============================================================================

CREATE TABLE buyer_profiles (
  user_id                       NUMBER(19) NOT NULL,
  client_id                     NUMBER(19) NOT NULL,
  default_address_line          VARCHAR2(500),
  default_address_city          VARCHAR2(200),
  default_address_state         VARCHAR2(200),
  default_address_country       VARCHAR2(100),
  default_address_postal_code   VARCHAR2(20),
  default_address_latitude      NUMBER(10,7),
  default_address_longitude     NUMBER(10,7),
  buyer_type                    VARCHAR2(20) DEFAULT 'INDIVIDUAL' NOT NULL,
  corporate_name                VARCHAR2(500),
  corporate_tax_id              VARCHAR2(100),
  created_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_buyer_profiles PRIMARY KEY (user_id, client_id),
  CONSTRAINT fk_bp_user FOREIGN KEY (user_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT chk_bp_buyer_type CHECK (buyer_type IN ('INDIVIDUAL', 'CORPORATE'))
);


CREATE TABLE courier_profiles (
  user_id            NUMBER(19) NOT NULL,
  client_id          NUMBER(19) NOT NULL,
  transport_method   VARCHAR2(100),
  vehicle_plate      VARCHAR2(50),
  additional_data    CLOB,
  created_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_courier_profiles PRIMARY KEY (user_id, client_id),
  CONSTRAINT fk_cp_user FOREIGN KEY (user_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT chk_cp_additional_json CHECK (additional_data IS JSON)
);


-- ============================================================================
-- SECCIÓN 5. TABLAS DE AUTENTICACIÓN
-- ============================================================================

CREATE TABLE sessions (
  id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id                NUMBER(19) NOT NULL,
  user_id                  NUMBER(19) NOT NULL,
  refresh_token_hash       VARCHAR2(500) NOT NULL,
  control_view_session_id  NUMBER(19),
  ip_address               VARCHAR2(45),
  user_agent               VARCHAR2(2000),
  issued_at                TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  last_used_at             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  expires_at               TIMESTAMP WITH TIME ZONE NOT NULL,
  revoked_at               TIMESTAMP WITH TIME ZONE,
  revocation_reason        VARCHAR2(200),

  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id, client_id) REFERENCES users(id, client_id)
);


CREATE TABLE control_view_master_passwords (
  user_id                 NUMBER(19) NOT NULL,
  client_id               NUMBER(19) DEFAULT 0 NOT NULL,
  master_password_hash    VARCHAR2(500) NOT NULL,
  can_use_control_view    CHAR(1) DEFAULT 'N' NOT NULL,
  set_at                  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  expires_at              TIMESTAMP WITH TIME ZONE,

  CONSTRAINT pk_cvmp PRIMARY KEY (user_id, client_id),
  CONSTRAINT fk_cvmp_user FOREIGN KEY (user_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT chk_cvmp_admin_ruta CHECK (client_id = 0),
  CONSTRAINT chk_cvmp_can_use CHECK (can_use_control_view IN ('Y', 'N'))
);


CREATE TABLE control_view_sessions (
  id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_ruta_user_id       NUMBER(19) NOT NULL,
  impersonated_client_id   NUMBER(19) NOT NULL,
  started_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ended_at                 TIMESTAMP WITH TIME ZONE,
  reason                   VARCHAR2(2000),
  ip_address               VARCHAR2(45),
  user_agent               VARCHAR2(2000),

  CONSTRAINT fk_cvs_client FOREIGN KEY (impersonated_client_id) REFERENCES clients(id)
);

ALTER TABLE sessions
  ADD CONSTRAINT fk_sessions_cvs FOREIGN KEY (control_view_session_id)
    REFERENCES control_view_sessions(id);


-- ============================================================================
-- SECCIÓN 6. API KEYS
-- ============================================================================

CREATE TABLE client_api_keys (
  id                   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id            NUMBER(19) NOT NULL,
  key_id               VARCHAR2(100) NOT NULL,
  secret_hash          VARCHAR2(500) NOT NULL,
  scopes               VARCHAR2(2000) NOT NULL,
  name                 VARCHAR2(200),
  last_used_at         TIMESTAMP WITH TIME ZONE,
  last_used_ip         VARCHAR2(45),
  expires_at           TIMESTAMP WITH TIME ZONE,
  revoked_at           TIMESTAMP WITH TIME ZONE,
  revocation_reason    VARCHAR2(200),
  created_by_user_id   NUMBER(19),
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_client_api_keys PRIMARY KEY (id, client_id),
  CONSTRAINT uk_cak_key_id UNIQUE (key_id),
  CONSTRAINT fk_cak_client FOREIGN KEY (client_id) REFERENCES clients(id)
);


-- ============================================================================
-- SECCIÓN 7. PROVEEDORES DE PAGO DEL CLIENTE
-- ============================================================================

CREATE TABLE client_payment_providers (
  id                             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                      NUMBER(19) NOT NULL,
  provider_type                  VARCHAR2(50) NOT NULL,
  provider_name                  VARCHAR2(200) NOT NULL,
  display_name                   VARCHAR2(200),
  config                         CLOB,
  webhook_ingress_path           VARCHAR2(500),
  webhook_secret                 VARCHAR2(500),
  status                         VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  is_default                     CHAR(1) DEFAULT 'N' NOT NULL,
  applicable_payment_methods     VARCHAR2(500) NOT NULL,
  created_at                     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_cpp PRIMARY KEY (id, client_id),
  CONSTRAINT fk_cpp_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT chk_cpp_provider_type CHECK (
    provider_type IN ('PAYMENT_GATEWAY', 'DATAFONO', 'BANK_TRANSFER', 'PAYMENT_LINK', 'QR')
  ),
  CONSTRAINT chk_cpp_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT chk_cpp_default CHECK (is_default IN ('Y', 'N')),
  CONSTRAINT chk_cpp_config_json CHECK (config IS JSON)
);


-- ============================================================================
-- SECCIÓN 8. PICKUP POINTS
-- ============================================================================

CREATE TABLE pickup_points (
  id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id       NUMBER(19) NOT NULL,
  name            VARCHAR2(300) NOT NULL,
  address_line    VARCHAR2(500) NOT NULL,
  city            VARCHAR2(200),
  state           VARCHAR2(200),
  country         VARCHAR2(100),
  postal_code     VARCHAR2(20),
  latitude        NUMBER(10,7),
  longitude       NUMBER(10,7),
  opening_hours   CLOB,
  contact_phone   VARCHAR2(50),
  status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_pickup_points PRIMARY KEY (id, client_id),
  CONSTRAINT fk_pp_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT chk_pp_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT chk_pp_hours_json CHECK (opening_hours IS JSON)
);


-- ============================================================================
-- SECCIÓN 9. CATÁLOGO DE PRODUCTOS
-- ============================================================================

CREATE TABLE product_categories (
  id                   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id            NUMBER(19) NOT NULL,
  name                 VARCHAR2(300) NOT NULL,
  parent_category_id   NUMBER(19),
  display_order        NUMBER(10),
  status               VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_product_categories PRIMARY KEY (id, client_id),
  CONSTRAINT fk_pc_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT chk_pc_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE TABLE products (
  id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id        NUMBER(19) NOT NULL,
  sku              VARCHAR2(200),
  name             VARCHAR2(500) NOT NULL,
  description      CLOB,
  product_type     VARCHAR2(30) DEFAULT 'VENTA_NORMAL' NOT NULL,
  unit_price       NUMBER(12,2) NOT NULL,
  currency         VARCHAR2(10) DEFAULT 'COP' NOT NULL,
  category_id      NUMBER(19),
  image_url        VARCHAR2(2000),
  status           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  stock_quantity   NUMBER(10),
  metadata         CLOB,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_products PRIMARY KEY (id, client_id),
  CONSTRAINT uk_products_client_sku UNIQUE (client_id, sku),
  CONSTRAINT fk_products_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT chk_products_type CHECK (product_type IN ('VENTA_NORMAL', 'PROMOCION')),
  CONSTRAINT chk_products_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT chk_products_metadata_json CHECK (metadata IS JSON)
);


-- ============================================================================
-- SECCIÓN 10. PLANTILLAS DE RECURRENCIA
-- ============================================================================

CREATE TABLE recurrence_templates (
  id                            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                     NUMBER(19) NOT NULL,
  buyer_id                      NUMBER(19) NOT NULL,
  recurrence_mode               VARCHAR2(30) NOT NULL,
  recurrence_periodicity        VARCHAR2(30),
  custom_interval_days          NUMBER(10),
  recurrence_status             VARCHAR2(30) DEFAULT 'RECURRENCE_ACTIVE' NOT NULL,
  delivery_type                 VARCHAR2(20) NOT NULL,
  delivery_carrier_type         VARCHAR2(30),
  payment_method                VARCHAR2(30) NOT NULL,
  payment_method_submethod      VARCHAR2(30),
  payment_provider_id           NUMBER(19),
  pickup_point_id               NUMBER(19),
  template_payload              CLOB NOT NULL,
  last_generated_at             TIMESTAMP WITH TIME ZONE,
  next_generation_at            TIMESTAMP WITH TIME ZONE,
  created_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_recurrence_templates PRIMARY KEY (id, client_id),
  CONSTRAINT fk_rt_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_rt_buyer FOREIGN KEY (buyer_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT fk_rt_payment_provider FOREIGN KEY (payment_provider_id, client_id)
    REFERENCES client_payment_providers(id, client_id),
  CONSTRAINT fk_rt_pickup_point FOREIGN KEY (pickup_point_id, client_id)
    REFERENCES pickup_points(id, client_id),
  CONSTRAINT chk_rt_mode CHECK (recurrence_mode IN ('SCHEDULED_RECURRING', 'REPEAT_LAST_ORDER')),
  CONSTRAINT chk_rt_periodicity CHECK (
    recurrence_periodicity IS NULL OR recurrence_periodicity IN
    ('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'CUSTOM_INTERVAL')
  ),
  CONSTRAINT chk_rt_status CHECK (
    recurrence_status IN ('RECURRENCE_ACTIVE', 'RECURRENCE_PAUSED', 'RECURRENCE_CANCELLED')
  ),
  CONSTRAINT chk_rt_delivery_type CHECK (delivery_type IN ('SHIP', 'PICKUP')),
  CONSTRAINT chk_rt_carrier_type CHECK (
    delivery_carrier_type IS NULL OR delivery_carrier_type IN ('OWN_FLEET', 'EXTERNAL_COURIER')
  ),
  CONSTRAINT chk_rt_payment_method CHECK (
    payment_method IN ('ONLINE_AT_ORDER', 'ELECTRONIC_ON_DELIVERY', 'CASH_ON_DELIVERY')
  ),
  CONSTRAINT chk_rt_payload_json CHECK (template_payload IS JSON)
);


-- ============================================================================
-- SECCIÓN 11. TABLA PRINCIPAL: orders
-- ============================================================================

CREATE TABLE orders (
  id                              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                       NUMBER(19) NOT NULL,
  buyer_id                        NUMBER(19) NOT NULL,
  courier_user_id                 NUMBER(19),
  order_origin                    VARCHAR2(40) NOT NULL,
  order_status                    VARCHAR2(50) NOT NULL,
  payment_status                  VARCHAR2(40) NOT NULL,
  refund_status                   VARCHAR2(40) DEFAULT 'REFUND_NOT_REQUIRED' NOT NULL,
  return_status                   VARCHAR2(40),
  dispute_status                  VARCHAR2(30),
  delivery_type                   VARCHAR2(20) NOT NULL,
  delivery_carrier_type           VARCHAR2(30),
  payment_method                  VARCHAR2(30) NOT NULL,
  payment_method_submethod        VARCHAR2(30),
  refund_modality                 VARCHAR2(20),
  return_mechanism                VARCHAR2(40),
  buyer_type                      VARCHAR2(20) DEFAULT 'INDIVIDUAL' NOT NULL,
  closure_reason                  VARCHAR2(40),
  payment_provider_id             NUMBER(19),
  external_payment_reference      VARCHAR2(200),
  recurrence_template_id          NUMBER(19),
  delivery_address_line           VARCHAR2(500),
  delivery_address_city           VARCHAR2(200),
  delivery_address_state          VARCHAR2(200),
  delivery_address_country        VARCHAR2(100),
  delivery_address_postal_code    VARCHAR2(20),
  delivery_address_latitude       NUMBER(10,7),
  delivery_address_longitude      NUMBER(10,7),
  delivery_instructions           VARCHAR2(2000),
  pickup_point_id                 NUMBER(19),
  subtotal                        NUMBER(12,2) DEFAULT 0 NOT NULL,
  tax                             NUMBER(12,2) DEFAULT 0 NOT NULL,
  shipping_fee                    NUMBER(12,2) DEFAULT 0 NOT NULL,
  discount                        NUMBER(12,2) DEFAULT 0 NOT NULL,
  total                           NUMBER(12,2) DEFAULT 0 NOT NULL,
  currency                        VARCHAR2(10) DEFAULT 'COP' NOT NULL,
  version                         NUMBER(19) DEFAULT 1 NOT NULL,
  created_at                      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  submitted_at                    TIMESTAMP WITH TIME ZONE,
  delivered_at                    TIMESTAMP WITH TIME ZONE,
  closed_at                       TIMESTAMP WITH TIME ZONE,
  archived                        CHAR(1) DEFAULT 'N' NOT NULL,
  archived_at                     TIMESTAMP WITH TIME ZONE,

  CONSTRAINT pk_orders PRIMARY KEY (id, client_id),
  CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT fk_orders_courier FOREIGN KEY (courier_user_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT fk_orders_payment_provider FOREIGN KEY (payment_provider_id, client_id)
    REFERENCES client_payment_providers(id, client_id),
  CONSTRAINT fk_orders_pickup_point FOREIGN KEY (pickup_point_id, client_id)
    REFERENCES pickup_points(id, client_id),
  CONSTRAINT fk_orders_recurrence FOREIGN KEY (recurrence_template_id, client_id)
    REFERENCES recurrence_templates(id, client_id),

  CONSTRAINT chk_orders_origin CHECK (order_origin IN (
    'BUYER_UI', 'CORPORATE_MANUAL', 'RECURRENCE',
    'FULL_LANDING_API', 'API_LOGISTICS'
  )),
  CONSTRAINT chk_orders_order_status CHECK (order_status IN (
    'DRAFT', 'PENDING_CONFIRM', 'ORDER_SUBMITTED', 'EXPIRED',
    'ORDER_VALIDATING', 'MANUAL_REVIEW', 'VALIDATION_APPROVED',
    'VALIDATION_REJECTED', 'SELLER_CONFIRMED', 'PREPARING',
    'AWAITING_COURIER_ASSIGNMENT', 'COURIER_ASSIGNED',
    'READY_TO_SHIP', 'READY_FOR_PICKUP',
    'SHIPMENT_HOLD', 'SHIPPED', 'IN_TRANSIT', 'ON_HOLD',
    'OUT_FOR_DELIVERY', 'ARRIVED_AT_CUSTOMER',
    'DELIVERY_ATTEMPTED', 'DELIVERY_RESCHEDULED', 'LOST_IN_TRANSIT',
    'AT_PICKUP_POINT', 'CUSTOMER_ARRIVED_AT_PICKUP_POINT',
    'IDENTITY_VALIDATED', 'PICKUP_AUTH_FAILED', 'PICKUP_POINT_ISSUE',
    'PICKUP_EXPIRED', 'PICKUP_CANCELLED_BY_CUSTOMER', 'PICKED_UP',
    'PAYMENT_COLLECTION_PENDING', 'PAYMENT_COLLECTED_ELECTRONIC',
    'PAYMENT_COLLECTED_CASH', 'CASH_COLLECTION_PENDING',
    'CASH_PAYMENT_REJECTED',
    'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_SELLER',
    'CANCELLED_BY_SYSTEM', 'CANCELLED_BY_ADMIN', 'CANCELLED_NO_PAYMENT',
    'CUSTOMER_CANCEL_REQUEST', 'CANCEL_REQUEST_APPROVED',
    'CANCEL_REQUEST_REJECTED',
    'RETURN_TO_ORIGIN', 'RETURN_TO_ORIGIN_RECEIVED', 'LOST_IN_RETURN',
    'DELIVERED', 'DELIVERY_DISPUTED', 'CONFIRMED_BY_CUSTOMER',
    'CONFIRMED_BY_SYSTEM', 'COMPLETED_SUCCESSFULLY', 'CLOSED'
  )),
  CONSTRAINT chk_orders_payment_status CHECK (payment_status IN (
    'PAYMENT_NOT_STARTED', 'PENDING_ONLINE_PAYMENT',
    'PAYMENT_PROCESSING', 'PAID',
    'PAYMENT_FAILED_RETRYABLE', 'PAYMENT_REJECTED_FINAL',
    'PENDING_COLLECTION', 'COLLECTION_PROCESSING',
    'PAYMENT_COLLECTED', 'PAYMENT_COLLECTION_FAILED',
    'PAYMENT_NOT_COLLECTED'
  )),
  CONSTRAINT chk_orders_refund_status CHECK (refund_status IN (
    'REFUND_NOT_REQUIRED', 'REFUND_PENDING', 'REFUND_PROCESSING',
    'REFUND_PROVIDER_REQUESTED', 'REFUNDED', 'PARTIALLY_REFUNDED',
    'REFUND_FAILED'
  )),
  CONSTRAINT chk_orders_return_status CHECK (
    return_status IS NULL OR return_status IN (
      'RETURN_REQUESTED', 'RETURN_UNDER_REVIEW', 'RETURN_APPROVED',
      'RETURN_REJECTED', 'RETURN_CANCELLED',
      'CUSTOMER_RETURN_IN_TRANSIT', 'CUSTOMER_RETURN_EXPIRED',
      'CUSTOMER_RETURN_RECEIVED', 'CUSTOMER_RETURN_LOST',
      'PICKUP_SCHEDULED', 'PICKUP_OUT_FOR_COLLECTION',
      'PICKUP_COLLECTED', 'PICKUP_FAILED'
    )
  ),
  CONSTRAINT chk_orders_dispute_status CHECK (
    dispute_status IS NULL OR dispute_status IN ('DISPUTED', 'DISPUTE_RESOLVED')
  ),
  CONSTRAINT chk_orders_delivery_type CHECK (delivery_type IN ('SHIP', 'PICKUP')),
  CONSTRAINT chk_orders_carrier_type CHECK (
    delivery_carrier_type IS NULL OR delivery_carrier_type IN ('OWN_FLEET', 'EXTERNAL_COURIER')
  ),
  CONSTRAINT chk_orders_payment_method CHECK (payment_method IN (
    'ONLINE_AT_ORDER', 'ELECTRONIC_ON_DELIVERY',
    'CASH_ON_DELIVERY', 'EXTERNAL_PREPAID'
  )),
  CONSTRAINT chk_orders_submethod CHECK (
    payment_method_submethod IS NULL OR payment_method_submethod IN
    ('DATAFONO', 'BANK_TRANSFER', 'PAYMENT_LINK', 'QR_OR_PAYMENT_LINK')
  ),
  CONSTRAINT chk_orders_refund_modality CHECK (
    refund_modality IS NULL OR refund_modality IN ('STORE_CREDIT', 'BANK_REFUND')
  ),
  CONSTRAINT chk_orders_return_mechanism CHECK (
    return_mechanism IS NULL OR return_mechanism IN
    ('BUYER_SHIPS_VIA_COURIER', 'CLIENT_PICKS_UP')
  ),
  CONSTRAINT chk_orders_buyer_type CHECK (buyer_type IN ('INDIVIDUAL', 'CORPORATE')),
  CONSTRAINT chk_orders_closure_reason CHECK (
    closure_reason IS NULL OR closure_reason IN (
      'COMPLETED_SUCCESSFULLY', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_SELLER',
      'CANCELLED_BY_SYSTEM', 'CANCELLED_BY_ADMIN', 'CANCELLED_NO_PAYMENT',
      'PAYMENT_TIMEOUT', 'PAYMENT_REJECTED', 'VALIDATION_REJECTED',
      'DELIVERY_FAILED', 'PICKUP_EXPIRED', 'LOST_IN_TRANSIT',
      'LOST_IN_RETURN', 'EXPIRED', 'CLIENT_DEACTIVATED'
    )
  ),
  CONSTRAINT chk_orders_archived CHECK (archived IN ('Y', 'N')),
  CONSTRAINT chk_orders_prepaid_origin CHECK (
    payment_method != 'EXTERNAL_PREPAID' OR order_origin = 'API_LOGISTICS'
  ),
  CONSTRAINT chk_orders_delivery_pickup CHECK (
    (delivery_type = 'SHIP' AND pickup_point_id IS NULL) OR
    (delivery_type = 'PICKUP')
  )
);


-- ============================================================================
-- SECCIÓN 12. ORDER ITEMS
-- ============================================================================

CREATE TABLE order_items (
  id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id     NUMBER(19) NOT NULL,
  order_id      NUMBER(19) NOT NULL,
  product_id    NUMBER(19),
  product_name  VARCHAR2(500) NOT NULL,
  sku           VARCHAR2(200),
  quantity      NUMBER(10) NOT NULL,
  unit_price    NUMBER(12,2) NOT NULL,
  subtotal      NUMBER(12,2) NOT NULL,
  metadata      CLOB,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_order_items PRIMARY KEY (id, client_id),
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id, client_id) REFERENCES orders(id, client_id),
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id, client_id) REFERENCES products(id, client_id),
  CONSTRAINT chk_oi_quantity CHECK (quantity > 0),
  CONSTRAINT chk_oi_metadata_json CHECK (metadata IS JSON)
);


-- ============================================================================
-- SECCIÓN 13. ORDER STATE HISTORY (append-only)
-- ============================================================================

CREATE TABLE order_state_history (
  id                     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id              NUMBER(19) NOT NULL,
  order_id               NUMBER(19) NOT NULL,
  state_dimension        VARCHAR2(30) NOT NULL,
  previous_value         VARCHAR2(50),
  new_value              VARCHAR2(50) NOT NULL,
  changed_by_user_id     NUMBER(19),
  changed_by_actor_type  VARCHAR2(30),
  reason                 VARCHAR2(2000),
  metadata               CLOB,
  occurred_at            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_order_state_history PRIMARY KEY (id, client_id),
  CONSTRAINT fk_osh_order FOREIGN KEY (order_id, client_id) REFERENCES orders(id, client_id),
  CONSTRAINT chk_osh_dimension CHECK (state_dimension IN (
    'order_status', 'payment_status', 'refund_status',
    'return_status', 'dispute_status'
  )),
  CONSTRAINT chk_osh_metadata_json CHECK (metadata IS JSON)
);


-- ============================================================================
-- SECCIÓN 14. PAGOS (trazabilidad — RUTA no custodia dinero)
-- ============================================================================

CREATE TABLE payments (
  id                            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                     NUMBER(19) NOT NULL,
  order_id                      NUMBER(19) NOT NULL,
  payment_provider_id           NUMBER(19),
  payment_method                VARCHAR2(30) NOT NULL,
  payment_method_submethod      VARCHAR2(30),
  amount                        NUMBER(12,2) NOT NULL,
  currency                      VARCHAR2(10) DEFAULT 'COP' NOT NULL,
  status                        VARCHAR2(30) NOT NULL,
  external_transaction_id       VARCHAR2(200),
  external_payment_reference    VARCHAR2(200),
  technical_confirmation_at     TIMESTAMP WITH TIME ZONE,
  collected_by_courier_user_id  NUMBER(19),
  collected_at                  TIMESTAMP WITH TIME ZONE,
  collection_evidence           CLOB,
  reconciled_with_client        CHAR(1) DEFAULT 'N' NOT NULL,
  reconciled_at                 TIMESTAMP WITH TIME ZONE,
  metadata                      CLOB,
  created_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_payments PRIMARY KEY (id, client_id),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id, client_id) REFERENCES orders(id, client_id),
  CONSTRAINT fk_payments_provider FOREIGN KEY (payment_provider_id, client_id)
    REFERENCES client_payment_providers(id, client_id),
  CONSTRAINT fk_payments_courier FOREIGN KEY (collected_by_courier_user_id, client_id)
    REFERENCES users(id, client_id),
  CONSTRAINT chk_payments_status CHECK (status IN (
    'PENDING', 'PROCESSING', 'CONFIRMED', 'FAILED', 'CANCELLED', 'COLLECTED_BY_COURIER'
  )),
  CONSTRAINT chk_payments_method CHECK (payment_method IN (
    'ONLINE_AT_ORDER', 'ELECTRONIC_ON_DELIVERY',
    'CASH_ON_DELIVERY', 'EXTERNAL_PREPAID'
  )),
  CONSTRAINT chk_payments_reconciled CHECK (reconciled_with_client IN ('Y', 'N')),
  CONSTRAINT chk_payments_evidence_json CHECK (collection_evidence IS JSON),
  CONSTRAINT chk_payments_metadata_json CHECK (metadata IS JSON)
);


-- ============================================================================
-- SECCIÓN 15. REEMBOLSOS (trazabilidad — el Cliente ejecuta)
-- ============================================================================

CREATE TABLE refunds (
  id                            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                     NUMBER(19) NOT NULL,
  order_id                      NUMBER(19) NOT NULL,
  payment_id                    NUMBER(19),
  refund_modality               VARCHAR2(20) NOT NULL,
  amount                        NUMBER(12,2) NOT NULL,
  currency                      VARCHAR2(10) DEFAULT 'COP' NOT NULL,
  status                        VARCHAR2(30) NOT NULL,
  executed_by_user_id           NUMBER(19),
  executed_at                   TIMESTAMP WITH TIME ZONE,
  external_provider_refund_id   VARCHAR2(200),
  evidence                      CLOB,
  reason                        VARCHAR2(2000),
  metadata                      CLOB,
  created_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_refunds PRIMARY KEY (id, client_id),
  CONSTRAINT fk_refunds_order FOREIGN KEY (order_id, client_id) REFERENCES orders(id, client_id),
  CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id, client_id) REFERENCES payments(id, client_id),
  CONSTRAINT fk_refunds_executor FOREIGN KEY (executed_by_user_id, client_id)
    REFERENCES users(id, client_id),
  CONSTRAINT chk_refunds_modality CHECK (refund_modality IN ('STORE_CREDIT', 'BANK_REFUND')),
  CONSTRAINT chk_refunds_status CHECK (status IN (
    'PENDING', 'PROCESSING', 'PROVIDER_REQUESTED',
    'REFUNDED', 'PARTIALLY_REFUNDED', 'FAILED'
  )),
  CONSTRAINT chk_refunds_evidence_json CHECK (evidence IS JSON),
  CONSTRAINT chk_refunds_metadata_json CHECK (metadata IS JSON)
);


-- ============================================================================
-- SECCIÓN 16. DEVOLUCIONES POST-CIERRE
-- ============================================================================

CREATE TABLE returns (
  id                       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                NUMBER(19) NOT NULL,
  order_id                 NUMBER(19) NOT NULL,
  buyer_id                 NUMBER(19) NOT NULL,
  status                   VARCHAR2(40) NOT NULL,
  return_mechanism         VARCHAR2(40),
  reason                   VARCHAR2(2000),
  buyer_complaint          CLOB,
  pickup_courier_user_id   NUMBER(19),
  requested_at             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  reviewed_at              TIMESTAMP WITH TIME ZONE,
  approved_at              TIMESTAMP WITH TIME ZONE,
  received_at              TIMESTAMP WITH TIME ZONE,
  closed_at                TIMESTAMP WITH TIME ZONE,
  evidence                 CLOB,
  metadata                 CLOB,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_returns PRIMARY KEY (id, client_id),
  CONSTRAINT fk_returns_order FOREIGN KEY (order_id, client_id) REFERENCES orders(id, client_id),
  CONSTRAINT fk_returns_buyer FOREIGN KEY (buyer_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT fk_returns_courier FOREIGN KEY (pickup_courier_user_id, client_id)
    REFERENCES users(id, client_id),
  CONSTRAINT chk_returns_status CHECK (status IN (
    'RETURN_REQUESTED', 'RETURN_UNDER_REVIEW', 'RETURN_APPROVED',
    'RETURN_REJECTED', 'RETURN_CANCELLED',
    'CUSTOMER_RETURN_IN_TRANSIT', 'CUSTOMER_RETURN_EXPIRED',
    'CUSTOMER_RETURN_RECEIVED', 'CUSTOMER_RETURN_LOST',
    'PICKUP_SCHEDULED', 'PICKUP_OUT_FOR_COLLECTION',
    'PICKUP_COLLECTED', 'PICKUP_FAILED'
  )),
  CONSTRAINT chk_returns_mechanism CHECK (
    return_mechanism IS NULL OR return_mechanism IN
    ('BUYER_SHIPS_VIA_COURIER', 'CLIENT_PICKS_UP')
  ),
  CONSTRAINT chk_returns_evidence_json CHECK (evidence IS JSON),
  CONSTRAINT chk_returns_metadata_json CHECK (metadata IS JSON)
);


-- ============================================================================
-- SECCIÓN 17. DISPUTAS
-- ============================================================================

CREATE TABLE disputes (
  id                     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id              NUMBER(19) NOT NULL,
  order_id               NUMBER(19) NOT NULL,
  buyer_id               NUMBER(19) NOT NULL,
  status                 VARCHAR2(30) DEFAULT 'DISPUTED' NOT NULL,
  reason                 VARCHAR2(2000),
  resolution             VARCHAR2(2000),
  resolution_action      VARCHAR2(40),
  resolved_by_user_id    NUMBER(19),
  resolved_at            TIMESTAMP WITH TIME ZONE,
  evidence               CLOB,
  created_at             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at             TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_disputes PRIMARY KEY (id, client_id),
  CONSTRAINT fk_disputes_order FOREIGN KEY (order_id, client_id) REFERENCES orders(id, client_id),
  CONSTRAINT fk_disputes_buyer FOREIGN KEY (buyer_id, client_id) REFERENCES users(id, client_id),
  CONSTRAINT fk_disputes_resolver FOREIGN KEY (resolved_by_user_id, client_id)
    REFERENCES users(id, client_id),
  CONSTRAINT chk_disputes_status CHECK (status IN ('DISPUTED', 'DISPUTE_RESOLVED')),
  CONSTRAINT chk_disputes_action CHECK (
    resolution_action IS NULL OR resolution_action IN
    ('NONE', 'APPROVE_RETURN', 'APPROVE_REFUND_NO_RETURN')
  ),
  CONSTRAINT chk_disputes_evidence_json CHECK (evidence IS JSON)
);


-- ============================================================================
-- SECCIÓN 18. WEBHOOKS
-- ============================================================================

CREATE TABLE webhook_subscriptions (
  id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id        NUMBER(19) NOT NULL,
  url              VARCHAR2(2000) NOT NULL,
  events           VARCHAR2(2000) NOT NULL,
  signing_secret   VARCHAR2(500) NOT NULL,
  status           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  description      VARCHAR2(500),
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_webhook_subscriptions PRIMARY KEY (id, client_id),
  CONSTRAINT fk_ws_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT chk_ws_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE TABLE webhook_deliveries (
  id                    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id             NUMBER(19) NOT NULL,
  subscription_id       NUMBER(19) NOT NULL,
  event_type            VARCHAR2(100) NOT NULL,
  event_id              VARCHAR2(200) NOT NULL,
  payload               CLOB NOT NULL,
  attempt_number        NUMBER(10) DEFAULT 1 NOT NULL,
  response_status       NUMBER(10),
  response_body         CLOB,
  delivered_at          TIMESTAMP WITH TIME ZONE,
  next_retry_at         TIMESTAMP WITH TIME ZONE,
  failed_permanently    CHAR(1) DEFAULT 'N' NOT NULL,
  created_at            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_webhook_deliveries PRIMARY KEY (id, client_id),
  CONSTRAINT fk_wd_subscription FOREIGN KEY (subscription_id) REFERENCES webhook_subscriptions(id),
  CONSTRAINT chk_wd_failed CHECK (failed_permanently IN ('Y', 'N')),
  CONSTRAINT chk_wd_payload_json CHECK (payload IS JSON)
);


CREATE TABLE external_webhook_events (
  id                    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id             NUMBER(19) NOT NULL,
  payment_provider_id   NUMBER(19) NOT NULL,
  provider_event_id     VARCHAR2(200) NOT NULL,
  payload               CLOB NOT NULL,
  signature_valid       CHAR(1),
  processed_at          TIMESTAMP WITH TIME ZONE,
  processing_result     VARCHAR2(2000),
  related_order_id      NUMBER(19),
  received_at           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT uk_ewe_provider_event UNIQUE (payment_provider_id, provider_event_id),
  CONSTRAINT chk_ewe_signature CHECK (signature_valid IS NULL OR signature_valid IN ('Y', 'N')),
  CONSTRAINT chk_ewe_payload_json CHECK (payload IS JSON)
);


-- ============================================================================
-- SECCIÓN 19. AUDITORÍA (append-only)
-- ============================================================================

CREATE TABLE audit_events (
  id                          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                   NUMBER(19) NOT NULL,
  actor_user_id               NUMBER(19),
  actor_api_key_id            NUMBER(19),
  actor_type                  VARCHAR2(30),
  actor_role                  VARCHAR2(30),
  acting_via_control_view     CHAR(1) DEFAULT 'N' NOT NULL,
  impersonator_user_id        NUMBER(19),
  control_view_session_id     NUMBER(19),
  action                      VARCHAR2(100) NOT NULL,
  entity_type                 VARCHAR2(50) NOT NULL,
  entity_id                   NUMBER(19),
  ip_address                  VARCHAR2(45),
  user_agent                  VARCHAR2(2000),
  metadata                    CLOB,
  result                      VARCHAR2(20) NOT NULL,
  occurred_at                 TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_audit_events PRIMARY KEY (id, client_id),
  CONSTRAINT chk_audit_acting_cv CHECK (acting_via_control_view IN ('Y', 'N')),
  CONSTRAINT chk_audit_result CHECK (result IN ('SUCCESS', 'FAILURE', 'DENIED')),
  CONSTRAINT chk_audit_metadata_json CHECK (metadata IS JSON)
);


-- ============================================================================
-- SECCIÓN 20. IDEMPOTENCY KEYS
-- ============================================================================

CREATE TABLE idempotency_keys (
  id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id         NUMBER(19) NOT NULL,
  actor_id          NUMBER(19) NOT NULL,
  actor_type        VARCHAR2(20) NOT NULL,
  idempotency_key   VARCHAR2(200) NOT NULL,
  request_hash      VARCHAR2(200) NOT NULL,
  response_status   NUMBER(10) NOT NULL,
  response_body     CLOB,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  expires_at        TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP + INTERVAL '24' HOUR) NOT NULL,

  CONSTRAINT pk_idempotency_keys PRIMARY KEY (id, client_id),
  CONSTRAINT uk_idem_unique UNIQUE (client_id, actor_type, actor_id, idempotency_key),
  CONSTRAINT chk_idem_actor_type CHECK (actor_type IN ('USER', 'API_KEY')),
  CONSTRAINT chk_idem_response_json CHECK (response_body IS JSON)
);


-- ============================================================================
-- SECCIÓN 21. CATÁLOGO DE ESTADOS
-- ============================================================================

CREATE TABLE state_catalog (
  state_dimension          VARCHAR2(30) NOT NULL,
  state_value              VARCHAR2(50) NOT NULL,
  description              VARCHAR2(500),
  is_terminal              CHAR(1) DEFAULT 'N' NOT NULL,
  display_order            NUMBER(10),
  applies_to_client_type   VARCHAR2(20) DEFAULT 'BOTH' NOT NULL,

  CONSTRAINT pk_state_catalog PRIMARY KEY (state_dimension, state_value),
  CONSTRAINT chk_sc_terminal CHECK (is_terminal IN ('Y', 'N')),
  CONSTRAINT chk_sc_applies CHECK (applies_to_client_type IN ('BOTH', 'FULL_ONLY', 'API_ONLY'))
);


-- ============================================================================
-- SECCIÓN 22. ÍNDICES
-- ============================================================================

CREATE INDEX idx_clients_status ON clients (status);
CREATE INDEX idx_clients_type ON clients (client_type);

CREATE INDEX idx_users_client_email ON users (client_id, email);
CREATE INDEX idx_users_client_type_status ON users (client_id, user_type, status);
CREATE INDEX idx_users_client_document ON users (client_id, document_type, document_number);

CREATE INDEX idx_sessions_user_active ON sessions (client_id, user_id, revoked_at);
CREATE INDEX idx_sessions_refresh_hash ON sessions (refresh_token_hash);
CREATE INDEX idx_sessions_expires ON sessions (expires_at);

CREATE INDEX idx_cak_key_id ON client_api_keys (key_id, revoked_at);

CREATE INDEX idx_cpp_client_status ON client_payment_providers (client_id, status);
CREATE INDEX idx_cpp_webhook_path ON client_payment_providers (webhook_ingress_path);

CREATE INDEX idx_products_client_status ON products (client_id, status);
CREATE INDEX idx_products_client_category ON products (client_id, category_id);

CREATE INDEX idx_orders_client_status ON orders (client_id, order_status);
CREATE INDEX idx_orders_client_buyer ON orders (client_id, buyer_id, order_status);
CREATE INDEX idx_orders_client_courier ON orders (client_id, courier_user_id);
CREATE INDEX idx_orders_client_created ON orders (client_id, created_at DESC);
CREATE INDEX idx_orders_client_payment ON orders (client_id, payment_status);
CREATE INDEX idx_orders_client_origin ON orders (client_id, order_origin);
CREATE INDEX idx_orders_client_refund ON orders (client_id, refund_status);
CREATE INDEX idx_orders_client_delivery ON orders (client_id, delivery_type);

CREATE INDEX idx_oi_client_order ON order_items (client_id, order_id);

CREATE INDEX idx_osh_client_order ON order_state_history (client_id, order_id, occurred_at DESC);
CREATE INDEX idx_osh_client_dim ON order_state_history (client_id, state_dimension, occurred_at DESC);

CREATE INDEX idx_payments_client_order ON payments (client_id, order_id);
CREATE INDEX idx_payments_client_status ON payments (client_id, status);
CREATE INDEX idx_payments_client_courier ON payments (client_id, collected_by_courier_user_id);
CREATE INDEX idx_payments_client_recon ON payments (client_id, reconciled_with_client);
CREATE INDEX idx_payments_external_txn ON payments (client_id, external_transaction_id);

CREATE INDEX idx_refunds_client_order ON refunds (client_id, order_id);
CREATE INDEX idx_refunds_client_status ON refunds (client_id, status);

CREATE INDEX idx_returns_client_order ON returns (client_id, order_id);
CREATE INDEX idx_returns_client_status ON returns (client_id, status);
CREATE INDEX idx_returns_client_buyer ON returns (client_id, buyer_id);

CREATE INDEX idx_disputes_client_order ON disputes (client_id, order_id);
CREATE INDEX idx_disputes_client_status ON disputes (client_id, status);

CREATE INDEX idx_audit_client_occurred ON audit_events (client_id, occurred_at DESC);
CREATE INDEX idx_audit_client_actor ON audit_events (client_id, actor_user_id, occurred_at DESC);
CREATE INDEX idx_audit_client_entity ON audit_events (client_id, entity_type, entity_id);
CREATE INDEX idx_audit_control_view ON audit_events (client_id, control_view_session_id);

CREATE INDEX idx_wd_client_subscription ON webhook_deliveries (client_id, subscription_id);
CREATE INDEX idx_wd_client_next_retry ON webhook_deliveries (client_id, next_retry_at);

CREATE INDEX idx_ewe_processed ON external_webhook_events (processed_at);

CREATE INDEX idx_idem_expires ON idempotency_keys (expires_at);

CREATE INDEX idx_rt_client_status ON recurrence_templates (client_id, recurrence_status);
CREATE INDEX idx_rt_next_generation ON recurrence_templates (next_generation_at, recurrence_status);


-- ============================================================================
-- SECCIÓN 23. TRIGGERS PARA updated_at
-- ============================================================================

CREATE OR REPLACE TRIGGER trg_clients_upd BEFORE UPDATE ON clients
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_users_upd BEFORE UPDATE ON users
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_buyer_profiles_upd BEFORE UPDATE ON buyer_profiles
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_courier_profiles_upd BEFORE UPDATE ON courier_profiles
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_cpp_upd BEFORE UPDATE ON client_payment_providers
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_pickup_points_upd BEFORE UPDATE ON pickup_points
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_pc_upd BEFORE UPDATE ON product_categories
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_products_upd BEFORE UPDATE ON products
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_rt_upd BEFORE UPDATE ON recurrence_templates
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_orders_upd BEFORE UPDATE ON orders
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_payments_upd BEFORE UPDATE ON payments
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_refunds_upd BEFORE UPDATE ON refunds
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_returns_upd BEFORE UPDATE ON returns
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_disputes_upd BEFORE UPDATE ON disputes
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_ws_upd BEFORE UPDATE ON webhook_subscriptions
FOR EACH ROW BEGIN :NEW.updated_at := SYSTIMESTAMP; END;
/


-- ============================================================================
-- SECCIÓN 24. CLIENTE PLATAFORMA
-- ============================================================================

INSERT INTO clients (
  id, business_code, slug, name, description, client_type, frontend_mode, status
) VALUES (
  0, 'RUTA-PLATFORM', 'ruta-platform', 'RUTA Platform',
  'Cliente especial que representa la plataforma. Aloja a los usuarios ADMIN_RUTA.',
  'FULL', 'NATIVE_RUTA', 'ACTIVE'
);


-- ============================================================================
-- SECCIÓN 25. CATÁLOGO DE ESTADOS (DATOS DE REFERENCIA)
-- ============================================================================

-- order_status
INSERT INTO state_catalog VALUES ('order_status', 'DRAFT', 'Pedido iniciado, sin confirmar', 'N', 10, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'PENDING_CONFIRM', 'Pendiente de confirmacion de entrega y pago', 'N', 20, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'ORDER_SUBMITTED', 'Pedido enviado al sistema', 'N', 30, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'EXPIRED', 'Pedido vencido sin confirmar', 'N', 40, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'ORDER_VALIDATING', 'En validacion operativa', 'N', 50, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'MANUAL_REVIEW', 'En revision humana', 'N', 60, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'VALIDATION_APPROVED', 'Validacion aprobada', 'N', 70, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'VALIDATION_REJECTED', 'Validacion rechazada', 'N', 80, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'SELLER_CONFIRMED', 'Aceptado por el vendedor', 'N', 90, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'PREPARING', 'En preparacion', 'N', 100, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'AWAITING_COURIER_ASSIGNMENT', 'Esperando asignacion de repartidor', 'N', 110, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'COURIER_ASSIGNED', 'Repartidor asignado', 'N', 120, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'READY_TO_SHIP', 'Listo para despacho', 'N', 130, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'READY_FOR_PICKUP', 'Listo para recogida', 'N', 140, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'SHIPMENT_HOLD', 'Despacho retenido', 'N', 150, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'SHIPPED', 'Despachado', 'N', 160, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'IN_TRANSIT', 'En transito', 'N', 170, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'ON_HOLD', 'Transito retenido', 'N', 180, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'OUT_FOR_DELIVERY', 'En reparto final', 'N', 190, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'ARRIVED_AT_CUSTOMER', 'Llegada al comprador', 'N', 200, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'DELIVERY_ATTEMPTED', 'Entrega intentada', 'N', 210, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'DELIVERY_RESCHEDULED', 'Entrega reprogramada', 'N', 220, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'LOST_IN_TRANSIT', 'Perdido en transito', 'Y', 230, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'AT_PICKUP_POINT', 'Disponible en punto fisico', 'N', 240, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CUSTOMER_ARRIVED_AT_PICKUP_POINT', 'Comprador llego a punto', 'N', 250, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'IDENTITY_VALIDATED', 'Identidad validada', 'N', 260, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PICKUP_AUTH_FAILED', 'Identidad no valida', 'N', 270, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PICKUP_POINT_ISSUE', 'Problema en punto fisico', 'N', 280, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PICKUP_EXPIRED', 'Plazo de pickup vencido', 'Y', 290, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PICKUP_CANCELLED_BY_CUSTOMER', 'Comprador no retira', 'Y', 300, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PICKED_UP', 'Recogido por comprador', 'N', 310, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PAYMENT_COLLECTION_PENDING', 'Cobro electronico pendiente', 'N', 320, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PAYMENT_COLLECTED_ELECTRONIC', 'Cobro electronico exitoso', 'N', 330, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'PAYMENT_COLLECTED_CASH', 'Cobro en efectivo exitoso', 'N', 340, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CASH_COLLECTION_PENDING', 'Cobro en efectivo pendiente', 'N', 350, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CASH_PAYMENT_REJECTED', 'Comprador no pago efectivo', 'N', 360, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CANCELLED_BY_CUSTOMER', 'Cancelado por comprador', 'Y', 370, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CANCELLED_BY_SELLER', 'Cancelado por vendedor', 'Y', 380, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'CANCELLED_BY_SYSTEM', 'Cancelado por sistema', 'Y', 390, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'CANCELLED_BY_ADMIN', 'Cancelado por administrador', 'Y', 400, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CANCELLED_NO_PAYMENT', 'Cancelado sin pago', 'Y', 410, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CUSTOMER_CANCEL_REQUEST', 'Solicitud de cancelacion post-despacho', 'N', 420, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CANCEL_REQUEST_APPROVED', 'Solicitud de cancelacion aprobada', 'N', 430, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CANCEL_REQUEST_REJECTED', 'Solicitud de cancelacion rechazada', 'N', 440, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'RETURN_TO_ORIGIN', 'Retorno al origen logistico', 'N', 450, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'RETURN_TO_ORIGIN_RECEIVED', 'Recibido en origen', 'N', 460, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'LOST_IN_RETURN', 'Perdido en retorno', 'Y', 470, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'DELIVERED', 'Entregado', 'N', 480, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'DELIVERY_DISPUTED', 'Entrega disputada', 'N', 490, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'CONFIRMED_BY_CUSTOMER', 'Confirmado por comprador', 'N', 500, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('order_status', 'CONFIRMED_BY_SYSTEM', 'Confirmado automaticamente', 'N', 510, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'COMPLETED_SUCCESSFULLY', 'Completado exitosamente', 'N', 520, 'BOTH');
INSERT INTO state_catalog VALUES ('order_status', 'CLOSED', 'Cerrado (estado final)', 'Y', 999, 'BOTH');

-- payment_status
INSERT INTO state_catalog VALUES ('payment_status', 'PAYMENT_NOT_STARTED', 'Pago no iniciado', 'N', 10, 'BOTH');
INSERT INTO state_catalog VALUES ('payment_status', 'PENDING_ONLINE_PAYMENT', 'Pendiente pago online', 'N', 20, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('payment_status', 'PAYMENT_PROCESSING', 'Pasarela procesando', 'N', 30, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('payment_status', 'PAID', 'Pagado', 'N', 40, 'BOTH');
INSERT INTO state_catalog VALUES ('payment_status', 'PAYMENT_FAILED_RETRYABLE', 'Pago fallido reintentable', 'N', 50, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('payment_status', 'PAYMENT_REJECTED_FINAL', 'Pago rechazado definitivamente', 'Y', 60, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('payment_status', 'PENDING_COLLECTION', 'Pendiente de cobro en entrega', 'N', 70, 'BOTH');
INSERT INTO state_catalog VALUES ('payment_status', 'COLLECTION_PROCESSING', 'Cobro electronico en proceso', 'N', 80, 'BOTH');
INSERT INTO state_catalog VALUES ('payment_status', 'PAYMENT_COLLECTED', 'Cobrado', 'N', 90, 'BOTH');
INSERT INTO state_catalog VALUES ('payment_status', 'PAYMENT_COLLECTION_FAILED', 'Cobro fallido reintentable', 'N', 100, 'BOTH');
INSERT INTO state_catalog VALUES ('payment_status', 'PAYMENT_NOT_COLLECTED', 'No se logro cobrar', 'Y', 110, 'BOTH');

-- refund_status
INSERT INTO state_catalog VALUES ('refund_status', 'REFUND_NOT_REQUIRED', 'No requiere reembolso', 'N', 10, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('refund_status', 'REFUND_PENDING', 'Reembolso pendiente', 'N', 20, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('refund_status', 'REFUND_PROCESSING', 'Reembolso en proceso', 'N', 30, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('refund_status', 'REFUND_PROVIDER_REQUESTED', 'Solicitado al proveedor', 'N', 40, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('refund_status', 'REFUNDED', 'Reembolsado totalmente', 'Y', 50, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('refund_status', 'PARTIALLY_REFUNDED', 'Reembolso parcial', 'Y', 60, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('refund_status', 'REFUND_FAILED', 'Reembolso fallido', 'N', 70, 'FULL_ONLY');

-- return_status
INSERT INTO state_catalog VALUES ('return_status', 'RETURN_REQUESTED', 'Devolucion solicitada', 'N', 10, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'RETURN_UNDER_REVIEW', 'En revision por el Cliente', 'N', 20, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'RETURN_APPROVED', 'Devolucion aprobada', 'N', 30, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'RETURN_REJECTED', 'Devolucion rechazada', 'Y', 40, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'RETURN_CANCELLED', 'Devolucion cancelada', 'Y', 50, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'CUSTOMER_RETURN_IN_TRANSIT', 'Producto en retorno (courier)', 'N', 60, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'CUSTOMER_RETURN_EXPIRED', 'Plazo de retorno vencido', 'Y', 70, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'CUSTOMER_RETURN_RECEIVED', 'Producto recibido', 'Y', 80, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'CUSTOMER_RETURN_LOST', 'Producto perdido en retorno', 'Y', 90, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'PICKUP_SCHEDULED', 'Recogida programada', 'N', 100, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'PICKUP_OUT_FOR_COLLECTION', 'Repartidor en camino a recoger', 'N', 110, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'PICKUP_COLLECTED', 'Producto recogido por repartidor', 'N', 120, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('return_status', 'PICKUP_FAILED', 'Fallo la recogida', 'N', 130, 'FULL_ONLY');

-- dispute_status
INSERT INTO state_catalog VALUES ('dispute_status', 'DISPUTED', 'Disputa abierta', 'N', 10, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('dispute_status', 'DISPUTE_RESOLVED', 'Disputa resuelta', 'Y', 20, 'FULL_ONLY');

-- recurrence_status
INSERT INTO state_catalog VALUES ('recurrence_status', 'RECURRENCE_ACTIVE', 'Plantilla activa', 'N', 10, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('recurrence_status', 'RECURRENCE_PAUSED', 'Plantilla pausada', 'N', 20, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('recurrence_status', 'RECURRENCE_CANCELLED', 'Plantilla cancelada', 'Y', 30, 'FULL_ONLY');

-- closure_reason
INSERT INTO state_catalog VALUES ('closure_reason', 'COMPLETED_SUCCESSFULLY', 'Pedido entregado y pago resuelto', 'Y', 10, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'CANCELLED_BY_CUSTOMER', 'Cancelado por el comprador', 'Y', 20, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'CANCELLED_BY_SELLER', 'Cancelado por el vendedor', 'Y', 30, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('closure_reason', 'CANCELLED_BY_SYSTEM', 'Cancelado por sistema', 'Y', 40, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('closure_reason', 'CANCELLED_BY_ADMIN', 'Cancelado por administrador', 'Y', 50, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'CANCELLED_NO_PAYMENT', 'Comprador no pago al entregar', 'Y', 60, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'PAYMENT_TIMEOUT', 'Pago online no completado a tiempo', 'Y', 70, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('closure_reason', 'PAYMENT_REJECTED', 'Pago online rechazado', 'Y', 80, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('closure_reason', 'VALIDATION_REJECTED', 'Rechazado por validacion', 'Y', 90, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('closure_reason', 'DELIVERY_FAILED', 'Entrega fallida definitiva', 'Y', 100, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'PICKUP_EXPIRED', 'Plazo de retiro vencido', 'Y', 110, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'LOST_IN_TRANSIT', 'Perdido en transito', 'Y', 120, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'LOST_IN_RETURN', 'Perdido en retorno', 'Y', 130, 'BOTH');
INSERT INTO state_catalog VALUES ('closure_reason', 'EXPIRED', 'Pedido vencido sin confirmar', 'Y', 140, 'FULL_ONLY');
INSERT INTO state_catalog VALUES ('closure_reason', 'CLIENT_DEACTIVATED', 'Cliente desactivado', 'Y', 150, 'BOTH');


-- ============================================================================
-- SECCIÓN ADICIONAL: client_parameters y operator_permissions
-- ============================================================================

CREATE TABLE client_parameters (
  id                              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  client_id                       NUMBER(19) NOT NULL,
  parameter_key                   VARCHAR2(200) NOT NULL,
  parameter_value                 VARCHAR2(4000) NOT NULL,
  value_type                      VARCHAR2(20) NOT NULL,
  description                     VARCHAR2(1000),
  is_overrideable_by_client       CHAR(1) DEFAULT 'Y' NOT NULL,
  created_at                      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_client_parameters PRIMARY KEY (id, client_id),
  CONSTRAINT uk_cparam_client_key UNIQUE (client_id, parameter_key),
  CONSTRAINT fk_cparam_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT chk_cparam_value_type CHECK (
    value_type IN ('INTEGER', 'DECIMAL', 'STRING', 'BOOLEAN', 'JSON')
  ),
  CONSTRAINT chk_cparam_overrideable CHECK (is_overrideable_by_client IN ('Y', 'N'))
);

COMMENT ON TABLE client_parameters IS
  'Parametros operativos. Valores globales en client_id=0; los Clientes pueden override.';


CREATE TABLE operator_permissions (
  operator_user_id      NUMBER(19) NOT NULL,
  client_id             NUMBER(19) NOT NULL,
  permission_key        VARCHAR2(100) NOT NULL,
  granted_at            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  granted_by_user_id    NUMBER(19) NOT NULL,

  CONSTRAINT pk_operator_permissions PRIMARY KEY (operator_user_id, client_id, permission_key),
  CONSTRAINT fk_op_user FOREIGN KEY (operator_user_id, client_id)
    REFERENCES users(id, client_id),
  CONSTRAINT fk_op_granter FOREIGN KEY (granted_by_user_id, client_id)
    REFERENCES users(id, client_id)
);

COMMENT ON TABLE operator_permissions IS
  'Permisos granulares por OPERATOR_CLIENT. ADMIN_CLIENT y ADMIN_RUTA tienen todos implicitamente.';


CREATE INDEX idx_cparam_client_key ON client_parameters (client_id, parameter_key);
CREATE INDEX idx_op_perm_user ON operator_permissions (client_id, operator_user_id);


-- ============================================================================
-- INSERTS: parametros globales por defecto (client_id = 0)
-- ============================================================================

-- Pedido
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'order.draft_expiration_minutes', '1440', 'INTEGER', 'Tiempo maximo en DRAFT', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'order.pending_confirm_timeout_minutes', '60', 'INTEGER', 'Tiempo maximo en PENDING_CONFIRM', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'order.pending_online_payment_timeout_minutes', '15', 'INTEGER', 'Tiempo maximo pago online', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'order.validation_max_duration_minutes', '5', 'INTEGER', 'Maximo en ORDER_VALIDATING', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'order.manual_review_sla_hours', '24', 'INTEGER', 'SLA para MANUAL_REVIEW', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'order.seller_confirmation_timeout_hours', '4', 'INTEGER', 'Tiempo aceptacion vendedor', 'Y');

-- SHIP
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ship.courier_assignment_timeout_minutes', '30', 'INTEGER', 'Timeout asignacion courier', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ship.preparation_max_hours', '24', 'INTEGER', 'Maximo en PREPARING', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ship.delivery_attempt_max_retries', '3', 'INTEGER', 'Intentos de entrega', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ship.delivery_attempt_retry_hours', '24', 'INTEGER', 'Tiempo entre intentos', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ship.in_transit_max_hours', '72', 'INTEGER', 'Maximo en IN_TRANSIT', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ship.cancel_request_review_hours', '2', 'INTEGER', 'Tiempo revisar CANCEL_REQUEST', 'Y');

-- PICKUP
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'pickup.expiration_hours', '48', 'INTEGER', 'Maximo en AT_PICKUP_POINT', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'pickup.notification_reminder_hours', '24', 'INTEGER', 'Recordatorio antes expiracion', 'Y');

-- Cierre
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'closure.auto_confirm_delivered_hours', '72', 'INTEGER', 'Auto-confirmacion post-DELIVERED', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'closure.dispute_window_hours', '72', 'INTEGER', 'Ventana para abrir disputa', 'Y');

-- Refunds
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'refund.processing_sla_business_days', '5', 'INTEGER', 'SLA reembolso', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'refund.provider_response_timeout_hours', '72', 'INTEGER', 'Timeout respuesta proveedor', 'Y');

-- Returns
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'return.review_sla_hours', '72', 'INTEGER', 'SLA aprobar devolucion', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'return.review_auto_action', 'APPROVE', 'STRING', 'Accion automatica sin respuesta', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'return.buyer_ships_deadline_days', '15', 'INTEGER', 'Plazo de despacho del Comprador', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'return.pickup_schedule_max_attempts', '2', 'INTEGER', 'Intentos recogida', 'Y');

-- Recurrencia
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'recurrence.generation_lookahead_hours', '24', 'INTEGER', 'Anticipacion generacion', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'recurrence.max_skipped_cycles', '3', 'INTEGER', 'Ciclos fallidos antes pausar', 'Y');

-- Auth
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.jwt_lifetime_admin_ruta_minutes', '15', 'INTEGER', 'JWT ADMIN_RUTA', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.jwt_lifetime_admin_client_minutes', '15', 'INTEGER', 'JWT ADMIN_CLIENT', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.jwt_lifetime_operator_client_minutes', '15', 'INTEGER', 'JWT OPERATOR_CLIENT', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.jwt_lifetime_buyer_minutes', '15', 'INTEGER', 'JWT BUYER', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.jwt_lifetime_courier_minutes', '30', 'INTEGER', 'JWT COURIER', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.refresh_token_lifetime_admin_days', '30', 'INTEGER', 'Refresh admin', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.refresh_token_lifetime_buyer_days', '90', 'INTEGER', 'Refresh buyer', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.refresh_token_lifetime_courier_days', '30', 'INTEGER', 'Refresh courier', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.max_failed_login_attempts', '5', 'INTEGER', 'Intentos fallidos', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.lockout_duration_minutes', '30', 'INTEGER', 'Duracion bloqueo', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.password_min_length', '10', 'INTEGER', 'Long minima password', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'auth.password_require_complexity', 'true', 'BOOLEAN', 'Complejidad password', 'N');

-- Vista de Control
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'control_view.master_password_rotation_days', '90', 'INTEGER', 'Rotacion recomendada', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'control_view.notify_admin_client', 'false', 'BOOLEAN', 'Notificar al ADMIN_CLIENT', 'N');

-- Webhooks
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'webhook.max_retries', '6', 'INTEGER', 'Reintentos webhook', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'webhook.retry_intervals_minutes', '[1,5,15,60,360,1440]', 'JSON', 'Intervalos de reintento', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'webhook.delivery_timeout_seconds', '10', 'INTEGER', 'Timeout HTTP', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'webhook.signing_algorithm', 'HMAC-SHA256', 'STRING', 'Algoritmo firma', 'N');

-- Idempotencia / Sesiones
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'idempotency.key_ttl_hours', '24', 'INTEGER', 'TTL idempotency keys', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'session.cleanup_after_revoked_days', '30', 'INTEGER', 'Limpieza sesiones revocadas', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'session.cleanup_after_expired_days', '30', 'INTEGER', 'Limpieza sesiones expiradas', 'N');

-- Cobranza
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'collection.electronic_retry_max_attempts', '3', 'INTEGER', 'Reintentos cobro electronico', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'collection.cash_change_max_amount', '100000', 'DECIMAL', 'Devuelta maxima efectivo', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'collection.evidence_required', 'true', 'BOOLEAN', 'Evidencia cobro obligatoria', 'Y');

-- Storage
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'storage.max_file_size_mb', '10', 'INTEGER', 'Tamano maximo archivo', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'storage.allowed_image_formats', '["jpg","jpeg","png","webp"]', 'JSON', 'Formatos permitidos', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'storage.evidence_retention_days', '730', 'INTEGER', 'Retencion evidencias', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'storage.product_image_max_count', '5', 'INTEGER', 'Imagenes por producto', 'Y');

-- Catalogo
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'catalog.bulk_import_max_rows', '5000', 'INTEGER', 'Filas por carga Excel', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'catalog.bulk_import_concurrent_max', '1', 'INTEGER', 'Imports simultaneos', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'catalog.default_currency', 'COP', 'STRING', 'Moneda por defecto', 'Y');

-- Mapa
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'map.provider', 'OSM', 'STRING', 'Proveedor de mapa', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'map.tile_cache_hours', '24', 'INTEGER', 'Cache de tiles', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'map.default_center_lat', '4.7110', 'DECIMAL', 'Centro Bogota', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'map.default_center_lng', '-74.0721', 'DECIMAL', 'Centro Bogota', 'Y');

-- Notificaciones
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'notifications.email_enabled', 'true', 'BOOLEAN', 'Email habilitado', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'notifications.sms_enabled', 'false', 'BOOLEAN', 'SMS habilitado', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'notifications.push_enabled', 'false', 'BOOLEAN', 'Push habilitado', 'Y');

-- Limites
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'limits.max_active_recurrences_per_buyer', '10', 'INTEGER', 'Recurrencias activas', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'limits.max_buyer_addresses', '10', 'INTEGER', 'Direcciones guardadas', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'limits.max_api_keys_per_client', '5', 'INTEGER', 'API keys activas', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'limits.max_pickup_points_per_client', '50', 'INTEGER', 'Puntos fisicos', 'Y');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'limits.max_couriers_per_client', '200', 'INTEGER', 'Repartidores activos', 'Y');

-- Rate limiting
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ratelimit.api_requests_per_minute_per_apikey', '300', 'INTEGER', 'Rate limit API key', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ratelimit.public_requests_per_minute_per_ip', '60', 'INTEGER', 'Rate limit publico', 'N');
INSERT INTO client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES (0, 'ratelimit.auth_attempts_per_minute_per_ip', '5', 'INTEGER', 'Rate limit auth', 'N');


COMMIT;


-- ============================================================================
-- FIN DEL MODELO DE DATOS ORACLE
-- ============================================================================
-- Notas para Oracle Data Modeler:
--   1. Importar via File → Import → DDL File.
--   2. El modelo refleja todas las tablas, FKs y constraints.
--   3. El particionamiento por client_id se implementa en producción
--      en el script PostgreSQL; para el DER no es necesario.
--   4. Los CHECK (col IS JSON) marcan columnas con contenido JSON.
--   5. Las tablas append-only (audit_events, order_state_history,
--      external_webhook_events, webhook_deliveries) deben tener
--      UPDATE/DELETE revocados en producción.
-- ============================================================================
