-- ============================================================================
-- RUTA — MODELO DE DATOS POSTGRESQL
-- ============================================================================
-- Plataforma multi-tenant para administración de operaciones comerciales
-- entre Clientes y Compradores.
--
-- Versión: 1.0
-- Schema: ruta
-- Base: PostgreSQL 14+
--
-- Este archivo crea el modelo de datos completo. Es ejecutable directo
-- sobre una base PostgreSQL limpia y reproduce toda la estructura
-- definida en docs/arquitectura/estrategia_multi_tenant_ruta.md y en
-- los 7 archivos de flujo (docs/flujos/flujo_*.txt).
--
-- Decisiones arquitectónicas reflejadas:
--   - Multi-tenant por client_id (BIGINT, no UUID).
--   - Particionamiento LIST por client_id con creación automática.
--   - Row Level Security activo en tablas operativas.
--   - Tablas append-only para auditoría e historial de estados.
--   - Soporte para Cliente API (Tipo A, solo logística) y Cliente Full
--     (Tipo B, ciclo completo).
--   - RUTA no custodia dinero: estados financieros para trazabilidad
--     y conciliación del Cliente.
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECCIÓN 1. SCHEMA Y EXTENSIONES
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS ruta;

SET search_path TO ruta, public;

-- Extensiones instaladas en schema 'public' (estándar). Si se instalan en
-- 'ruta', luego GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ruta intentaría
-- otorgar permisos sobre funciones del superuser (pgcrypto, btree_gin) y
-- generaría cientos de WARNINGs inofensivos pero ruidosos.
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA public;


-- ============================================================================
-- SECCIÓN 2. ROLES DE BASE DE DATOS
-- ============================================================================

DO $do$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ruta_app') THEN
    CREATE ROLE ruta_app NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ruta_jobs') THEN
    CREATE ROLE ruta_jobs NOLOGIN BYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ruta_readonly') THEN
    CREATE ROLE ruta_readonly NOLOGIN;
  END IF;
END
$do$;


-- ============================================================================
-- SECCIÓN 3. FUNCIONES AUXILIARES
-- ============================================================================

-- Trigger genérico: actualiza updated_at automáticamente
CREATE OR REPLACE FUNCTION ruta.trg_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- SECCIÓN 4. TABLA: clients
-- No particionada. Tabla central de tenants.
-- ============================================================================

CREATE TABLE ruta.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_code TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  contact_person_name TEXT,
  contact_person_document_type TEXT,
  contact_person_document_number TEXT,
  contact_person_phone TEXT,
  contact_person_email TEXT,
  logo_url TEXT,

  client_type TEXT NOT NULL
    CHECK (client_type IN ('API', 'FULL')),

  frontend_mode TEXT
    CHECK (frontend_mode IS NULL OR frontend_mode IN (
      'NATIVE_RUTA', 'CUSTOM_LANDING_BY_RUTA'
    )),

  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'INACTIVE')),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_clients_frontend_mode_type CHECK (
    (client_type = 'API' AND frontend_mode IS NULL) OR
    (client_type = 'FULL' AND frontend_mode IS NOT NULL)
  )
);

COMMENT ON TABLE ruta.clients IS
  'Tabla central de tenants. client_id = 0 representa la plataforma RUTA.';

CREATE TRIGGER trg_clients_updated_at
BEFORE UPDATE ON ruta.clients
FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();


-- ============================================================================
-- SECCIÓN 5. TABLA: users
-- Particionada por client_id. Tabla única para todos los usuarios.
-- ============================================================================

CREATE TABLE ruta.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  user_type TEXT NOT NULL
    CHECK (user_type IN (
      'ADMIN_RUTA',
      'ADMIN_CLIENT',
      'OPERATOR_CLIENT',
      'BUYER',
      'COURIER'
    )),

  email TEXT NOT NULL,
  password_hash TEXT,

  auth_mode TEXT NOT NULL DEFAULT 'PASSWORD'
    CHECK (auth_mode IN ('PASSWORD', 'EXTERNAL_REFERENCE')),
  external_buyer_id TEXT,

  full_name TEXT,
  document_type TEXT,
  document_number TEXT,
  phone TEXT,

  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),

  last_login_at TIMESTAMPTZ,
  password_changed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  UNIQUE (client_id, email),
  UNIQUE (client_id, external_buyer_id),

  CONSTRAINT fk_users_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id),

  CONSTRAINT chk_users_password_consistency CHECK (
    (auth_mode = 'PASSWORD' AND password_hash IS NOT NULL) OR
    (auth_mode = 'EXTERNAL_REFERENCE' AND password_hash IS NULL)
  )
) PARTITION BY LIST (client_id);

COMMENT ON TABLE ruta.users IS
  'Tabla única de usuarios. ADMIN_RUTA tiene client_id = 0.';


-- ============================================================================
-- SECCIÓN 6. TABLAS: buyer_profiles y courier_profiles
-- Datos operativos específicos de BUYER y COURIER.
-- ============================================================================

CREATE TABLE ruta.buyer_profiles (
  user_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  default_address_line TEXT,
  default_address_city TEXT,
  default_address_state TEXT,
  default_address_country TEXT,
  default_address_postal_code TEXT,
  default_address_latitude NUMERIC(10,7),
  default_address_longitude NUMERIC(10,7),
  buyer_type TEXT NOT NULL DEFAULT 'INDIVIDUAL'
    CHECK (buyer_type IN ('INDIVIDUAL', 'CORPORATE')),
  corporate_name TEXT,
  corporate_tax_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (user_id, client_id),
  CONSTRAINT fk_bp_user FOREIGN KEY (user_id, client_id)
    REFERENCES ruta.users(id, client_id)
) PARTITION BY LIST (client_id);


CREATE TABLE ruta.courier_profiles (
  user_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  transport_method TEXT,
  vehicle_plate TEXT,
  additional_data JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (user_id, client_id),
  CONSTRAINT fk_cp_user FOREIGN KEY (user_id, client_id)
    REFERENCES ruta.users(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 7. TABLAS DE AUTENTICACIÓN
-- ============================================================================

CREATE TABLE ruta.sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  refresh_token_hash TEXT NOT NULL,
  control_view_session_id BIGINT,
  ip_address INET,
  user_agent TEXT,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  revocation_reason TEXT,

  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id, client_id)
    REFERENCES ruta.users(id, client_id)
);

COMMENT ON TABLE ruta.sessions IS
  'Sesiones activas. No particionada porque las queries por
  refresh_token_hash no tienen contexto de client_id.';


CREATE TABLE ruta.control_view_master_passwords (
  user_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL DEFAULT 0,
  master_password_hash TEXT NOT NULL,
  can_use_control_view BOOLEAN NOT NULL DEFAULT FALSE,
  set_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  PRIMARY KEY (user_id, client_id),
  CONSTRAINT fk_cvmp_user FOREIGN KEY (user_id, client_id)
    REFERENCES ruta.users(id, client_id),
  CONSTRAINT chk_cvmp_admin_ruta CHECK (client_id = 0)
);


CREATE TABLE ruta.control_view_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_ruta_user_id BIGINT NOT NULL,
  impersonated_client_id BIGINT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  reason TEXT,
  ip_address INET,
  user_agent TEXT,
  CONSTRAINT fk_cvs_client FOREIGN KEY (impersonated_client_id)
    REFERENCES ruta.clients(id)
);

ALTER TABLE ruta.sessions
  ADD CONSTRAINT fk_sessions_cvs FOREIGN KEY (control_view_session_id)
    REFERENCES ruta.control_view_sessions(id);


-- ============================================================================
-- SECCIÓN 8. API KEYS
-- ============================================================================
-- NOTA: Esta tabla NO se particiona por client_id, a diferencia del resto
-- de tablas multi-tenant del modelo. Razones:
--   1. Volumen muy bajo (limits.max_api_keys_per_client = 5).
--   2. Lookup en cada request entrante por key_id sin conocer aún el client_id
--      → requiere unicidad GLOBAL de key_id, incompatible con
--      PARTITION BY LIST (client_id) en PostgreSQL.
--   3. Al dar de baja un cliente, la limpieza se hace con un DELETE explícito
--      en delete_client_permanently() — instantáneo a este volumen.
-- ============================================================================

CREATE TABLE ruta.client_api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  key_id TEXT UNIQUE NOT NULL,
  secret_hash TEXT NOT NULL,
  scopes TEXT[] NOT NULL,
  name TEXT,
  last_used_at TIMESTAMPTZ,
  last_used_ip INET,
  expires_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revocation_reason TEXT,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id),
  CONSTRAINT fk_cak_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id)
);


-- ============================================================================
-- SECCIÓN 9. PROVEEDORES DE PAGO CONFIGURABLES POR CLIENTE
-- ============================================================================

CREATE TABLE ruta.client_payment_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  provider_type TEXT NOT NULL
    CHECK (provider_type IN (
      'PAYMENT_GATEWAY', 'DATAFONO', 'BANK_TRANSFER', 'PAYMENT_LINK', 'QR'
    )),
  provider_name TEXT NOT NULL,
  display_name TEXT,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  webhook_ingress_path TEXT,
  webhook_secret TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'INACTIVE')),
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  applicable_payment_methods TEXT[] NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_cpp_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 10. PICKUP POINTS (puntos físicos del Cliente)
-- ============================================================================

CREATE TABLE ruta.pickup_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  address_line TEXT NOT NULL,
  city TEXT,
  state TEXT,
  country TEXT,
  postal_code TEXT,
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  opening_hours JSONB,
  contact_phone TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_pp_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 11. CATÁLOGO DE PRODUCTOS
-- ============================================================================

CREATE TABLE ruta.product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  parent_category_id BIGINT,
  display_order INT,
  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_pc_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id)
) PARTITION BY LIST (client_id);


CREATE TABLE ruta.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  sku TEXT,
  name TEXT NOT NULL,
  description TEXT,
  product_type TEXT NOT NULL DEFAULT 'VENTA_NORMAL'
    CHECK (product_type IN ('VENTA_NORMAL', 'PROMOCION')),
  unit_price NUMERIC(12,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'COP',
  category_id BIGINT,
  image_url TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'INACTIVE')),
  stock_quantity INT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  UNIQUE (client_id, sku),
  CONSTRAINT fk_products_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 12. RECURRENCIA (plantillas de pedidos recurrentes)
-- ============================================================================

CREATE TABLE ruta.recurrence_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  buyer_id BIGINT NOT NULL,
  recurrence_mode TEXT NOT NULL
    CHECK (recurrence_mode IN ('SCHEDULED_RECURRING', 'REPEAT_LAST_ORDER')),
  recurrence_periodicity TEXT
    CHECK (recurrence_periodicity IS NULL OR recurrence_periodicity IN (
      'DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'CUSTOM_INTERVAL'
    )),
  custom_interval_days INT,
  recurrence_status TEXT NOT NULL DEFAULT 'RECURRENCE_ACTIVE'
    CHECK (recurrence_status IN (
      'RECURRENCE_ACTIVE', 'RECURRENCE_PAUSED', 'RECURRENCE_CANCELLED'
    )),

  delivery_type TEXT NOT NULL
    CHECK (delivery_type IN ('SHIP', 'PICKUP')),
  delivery_carrier_type TEXT
    CHECK (delivery_carrier_type IS NULL OR delivery_carrier_type IN (
      'OWN_FLEET', 'EXTERNAL_COURIER'
    )),
  payment_method TEXT NOT NULL
    CHECK (payment_method IN (
      'ONLINE_AT_ORDER', 'ELECTRONIC_ON_DELIVERY', 'CASH_ON_DELIVERY'
    )),
  payment_method_submethod TEXT,
  payment_provider_id BIGINT,
  pickup_point_id BIGINT,

  template_payload JSONB NOT NULL,
  last_generated_at TIMESTAMPTZ,
  next_generation_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_rt_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id),
  CONSTRAINT fk_rt_buyer FOREIGN KEY (buyer_id, client_id)
    REFERENCES ruta.users(id, client_id),
  CONSTRAINT fk_rt_payment_provider FOREIGN KEY (payment_provider_id, client_id)
    REFERENCES ruta.client_payment_providers(id, client_id),
  CONSTRAINT fk_rt_pickup_point FOREIGN KEY (pickup_point_id, client_id)
    REFERENCES ruta.pickup_points(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 13. TABLA PRINCIPAL: orders
-- ============================================================================

CREATE TABLE ruta.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  buyer_id BIGINT NOT NULL,
  courier_user_id BIGINT,

  -- Origen del pedido
  order_origin TEXT NOT NULL
    CHECK (order_origin IN (
      'BUYER_UI',
      'CORPORATE_MANUAL',
      'RECURRENCE',
      'FULL_LANDING_API',
      'API_LOGISTICS'
    )),

  -- Estados separados por dominio
  order_status TEXT NOT NULL
    CHECK (order_status IN (
      'DRAFT', 'PENDING_CONFIRM', 'ORDER_SUBMITTED', 'EXPIRED',
      'ORDER_VALIDATING', 'MANUAL_REVIEW', 'VALIDATION_APPROVED',
      'VALIDATION_REJECTED', 'SELLER_CONFIRMED', 'PREPARING',
      'AWAITING_COURIER_ASSIGNMENT', 'COURIER_ASSIGNED',
      'READY_TO_SHIP', 'READY_FOR_PICKUP',
      'SHIPMENT_HOLD', 'SHIPPED', 'IN_TRANSIT', 'ON_HOLD',
      'OUT_FOR_DELIVERY', 'ARRIVED_AT_CUSTOMER',
      'DELIVERY_ATTEMPTED', 'DELIVERY_RESCHEDULED', 'LOST_IN_TRANSIT',
      'AT_PICKUP_POINT', 'CUSTOMER_ARRIVED_AT_PICKUP_POINT',
      'IDENTITY_VALIDATED', 'PICKUP_AUTH_FAILED', 'PICKUP_POINT_ISSUE',
      'PICKUP_EXPIRED', 'PICKUP_CANCELLED_BY_CUSTOMER', 'PICKED_UP',
      'PAYMENT_COLLECTION_PENDING', 'PAYMENT_COLLECTED_ELECTRONIC',
      'PAYMENT_COLLECTED_CASH', 'CASH_COLLECTION_PENDING',
      'CASH_PAYMENT_REJECTED',
      'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_SELLER',
      'CANCELLED_BY_SYSTEM', 'CANCELLED_BY_ADMIN', 'CANCELLED_NO_PAYMENT',
      'CUSTOMER_CANCEL_REQUEST', 'CANCEL_REQUEST_APPROVED',
      'CANCEL_REQUEST_REJECTED',
      'RETURN_TO_ORIGIN', 'RETURN_TO_ORIGIN_RECEIVED', 'LOST_IN_RETURN',
      'DELIVERED', 'DELIVERY_DISPUTED', 'CONFIRMED_BY_CUSTOMER',
      'CONFIRMED_BY_SYSTEM', 'COMPLETED_SUCCESSFULLY', 'CLOSED'
    )),

  payment_status TEXT NOT NULL
    CHECK (payment_status IN (
      'PAYMENT_NOT_STARTED', 'PENDING_ONLINE_PAYMENT',
      'PAYMENT_PROCESSING', 'PAID',
      'PAYMENT_FAILED_RETRYABLE', 'PAYMENT_REJECTED_FINAL',
      'PENDING_COLLECTION', 'COLLECTION_PROCESSING',
      'PAYMENT_COLLECTED', 'PAYMENT_COLLECTION_FAILED',
      'PAYMENT_NOT_COLLECTED'
    )),

  refund_status TEXT NOT NULL DEFAULT 'REFUND_NOT_REQUIRED'
    CHECK (refund_status IN (
      'REFUND_NOT_REQUIRED', 'REFUND_PENDING', 'REFUND_PROCESSING',
      'REFUND_PROVIDER_REQUESTED', 'REFUNDED', 'PARTIALLY_REFUNDED',
      'REFUND_FAILED'
    )),

  return_status TEXT
    CHECK (return_status IS NULL OR return_status IN (
      'RETURN_REQUESTED', 'RETURN_UNDER_REVIEW', 'RETURN_APPROVED',
      'RETURN_REJECTED', 'RETURN_CANCELLED',
      'CUSTOMER_RETURN_IN_TRANSIT', 'CUSTOMER_RETURN_EXPIRED',
      'CUSTOMER_RETURN_RECEIVED', 'CUSTOMER_RETURN_LOST',
      'PICKUP_SCHEDULED', 'PICKUP_OUT_FOR_COLLECTION',
      'PICKUP_COLLECTED', 'PICKUP_FAILED'
    )),

  dispute_status TEXT
    CHECK (dispute_status IS NULL OR dispute_status IN (
      'DISPUTED', 'DISPUTE_RESOLVED'
    )),

  -- Atributos de bifurcación (BLOQUE 0 de los flujos)
  delivery_type TEXT NOT NULL CHECK (delivery_type IN ('SHIP', 'PICKUP')),
  delivery_carrier_type TEXT
    CHECK (delivery_carrier_type IS NULL OR delivery_carrier_type IN (
      'OWN_FLEET', 'EXTERNAL_COURIER'
    )),

  payment_method TEXT NOT NULL
    CHECK (payment_method IN (
      'ONLINE_AT_ORDER',
      'ELECTRONIC_ON_DELIVERY',
      'CASH_ON_DELIVERY',
      'EXTERNAL_PREPAID'
    )),
  payment_method_submethod TEXT
    CHECK (payment_method_submethod IS NULL OR payment_method_submethod IN (
      'DATAFONO', 'BANK_TRANSFER', 'PAYMENT_LINK', 'QR_OR_PAYMENT_LINK'
    )),

  refund_modality TEXT
    CHECK (refund_modality IS NULL OR refund_modality IN (
      'STORE_CREDIT', 'BANK_REFUND'
    )),
  return_mechanism TEXT
    CHECK (return_mechanism IS NULL OR return_mechanism IN (
      'BUYER_SHIPS_VIA_COURIER', 'CLIENT_PICKS_UP'
    )),

  buyer_type TEXT NOT NULL DEFAULT 'INDIVIDUAL'
    CHECK (buyer_type IN ('INDIVIDUAL', 'CORPORATE')),

  closure_reason TEXT
    CHECK (closure_reason IS NULL OR closure_reason IN (
      'COMPLETED_SUCCESSFULLY', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_SELLER',
      'CANCELLED_BY_SYSTEM', 'CANCELLED_BY_ADMIN', 'CANCELLED_NO_PAYMENT',
      'PAYMENT_TIMEOUT', 'PAYMENT_REJECTED', 'VALIDATION_REJECTED',
      'DELIVERY_FAILED', 'PICKUP_EXPIRED', 'LOST_IN_TRANSIT',
      'LOST_IN_RETURN', 'EXPIRED', 'CLIENT_DEACTIVATED'
    )),

  -- Referencias
  payment_provider_id BIGINT,
  external_payment_reference TEXT,
  recurrence_template_id BIGINT,

  -- Dirección de entrega (para SHIP)
  delivery_address_line TEXT,
  delivery_address_city TEXT,
  delivery_address_state TEXT,
  delivery_address_country TEXT,
  delivery_address_postal_code TEXT,
  delivery_address_latitude NUMERIC(10,7),
  delivery_address_longitude NUMERIC(10,7),
  delivery_instructions TEXT,

  -- Punto de recogida (para PICKUP)
  pickup_point_id BIGINT,

  -- Financiero
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax NUMERIC(12,2) NOT NULL DEFAULT 0,
  shipping_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'COP',

  -- Concurrencia
  version BIGINT NOT NULL DEFAULT 1,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  submitted_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  archived_at TIMESTAMPTZ,

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id),
  CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id, client_id)
    REFERENCES ruta.users(id, client_id),
  CONSTRAINT fk_orders_courier FOREIGN KEY (courier_user_id, client_id)
    REFERENCES ruta.users(id, client_id),
  CONSTRAINT fk_orders_payment_provider FOREIGN KEY (payment_provider_id, client_id)
    REFERENCES ruta.client_payment_providers(id, client_id),
  CONSTRAINT fk_orders_pickup_point FOREIGN KEY (pickup_point_id, client_id)
    REFERENCES ruta.pickup_points(id, client_id),
  CONSTRAINT fk_orders_recurrence FOREIGN KEY (recurrence_template_id, client_id)
    REFERENCES ruta.recurrence_templates(id, client_id),

  -- Coherencia: EXTERNAL_PREPAID solo aplica para API_LOGISTICS
  CONSTRAINT chk_orders_prepaid_origin CHECK (
    payment_method != 'EXTERNAL_PREPAID' OR order_origin = 'API_LOGISTICS'
  ),
  -- Coherencia: SHIP no usa pickup_point; PICKUP sí
  CONSTRAINT chk_orders_delivery_pickup CHECK (
    (delivery_type = 'SHIP' AND pickup_point_id IS NULL) OR
    (delivery_type = 'PICKUP')
  )
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 14. ORDER ITEMS
-- ============================================================================

CREATE TABLE ruta.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  product_id BIGINT,
  product_name TEXT NOT NULL,
  sku TEXT,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12,2) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id, client_id)
    REFERENCES ruta.orders(id, client_id),
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id, client_id)
    REFERENCES ruta.products(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 15. ORDER STATE HISTORY (append-only)
-- ============================================================================

CREATE TABLE ruta.order_state_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  state_dimension TEXT NOT NULL
    CHECK (state_dimension IN (
      'order_status', 'payment_status', 'refund_status',
      'return_status', 'dispute_status'
    )),
  previous_value TEXT,
  new_value TEXT NOT NULL,
  changed_by_user_id BIGINT,
  changed_by_actor_type TEXT,
  reason TEXT,
  metadata JSONB,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_osh_order FOREIGN KEY (order_id, client_id)
    REFERENCES ruta.orders(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 16. PAGOS (registros de trazabilidad)
-- RUTA no custodia dinero; estos registros son para conciliación.
-- ============================================================================

CREATE TABLE ruta.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  payment_provider_id BIGINT,
  payment_method TEXT NOT NULL,
  payment_method_submethod TEXT,
  amount NUMERIC(12,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'COP',
  status TEXT NOT NULL
    CHECK (status IN (
      'PENDING', 'PROCESSING', 'CONFIRMED', 'FAILED', 'CANCELLED',
      'COLLECTED_BY_COURIER'
    )),

  -- Para pagos online (registro de la transacción del proveedor)
  external_transaction_id TEXT,
  external_payment_reference TEXT,
  technical_confirmation_at TIMESTAMPTZ,

  -- Para pago contra entrega
  collected_by_courier_user_id BIGINT,
  collected_at TIMESTAMPTZ,
  collection_evidence JSONB,

  -- Conciliación con Cliente
  reconciled_with_client BOOLEAN NOT NULL DEFAULT FALSE,
  reconciled_at TIMESTAMPTZ,

  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id, client_id)
    REFERENCES ruta.orders(id, client_id),
  CONSTRAINT fk_payments_provider FOREIGN KEY (payment_provider_id, client_id)
    REFERENCES ruta.client_payment_providers(id, client_id),
  CONSTRAINT fk_payments_courier FOREIGN KEY (collected_by_courier_user_id, client_id)
    REFERENCES ruta.users(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 17. REEMBOLSOS (registros de trazabilidad)
-- RUTA no transfiere dinero; estos registros son para trazar lo que el
-- Cliente ejecuta en su sistema o vía su proveedor.
-- ============================================================================

CREATE TABLE ruta.refunds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  payment_id BIGINT,
  refund_modality TEXT NOT NULL
    CHECK (refund_modality IN ('STORE_CREDIT', 'BANK_REFUND')),
  amount NUMERIC(12,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'COP',
  status TEXT NOT NULL
    CHECK (status IN (
      'PENDING', 'PROCESSING', 'PROVIDER_REQUESTED',
      'REFUNDED', 'PARTIALLY_REFUNDED', 'FAILED'
    )),
  executed_by_user_id BIGINT,
  executed_at TIMESTAMPTZ,
  external_provider_refund_id TEXT,
  evidence JSONB,
  reason TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_refunds_order FOREIGN KEY (order_id, client_id)
    REFERENCES ruta.orders(id, client_id),
  CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id, client_id)
    REFERENCES ruta.payments(id, client_id),
  CONSTRAINT fk_refunds_executor FOREIGN KEY (executed_by_user_id, client_id)
    REFERENCES ruta.users(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 18. DEVOLUCIONES POST-CIERRE
-- ============================================================================

CREATE TABLE ruta.returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  buyer_id BIGINT NOT NULL,
  status TEXT NOT NULL
    CHECK (status IN (
      'RETURN_REQUESTED', 'RETURN_UNDER_REVIEW', 'RETURN_APPROVED',
      'RETURN_REJECTED', 'RETURN_CANCELLED',
      'CUSTOMER_RETURN_IN_TRANSIT', 'CUSTOMER_RETURN_EXPIRED',
      'CUSTOMER_RETURN_RECEIVED', 'CUSTOMER_RETURN_LOST',
      'PICKUP_SCHEDULED', 'PICKUP_OUT_FOR_COLLECTION',
      'PICKUP_COLLECTED', 'PICKUP_FAILED'
    )),
  return_mechanism TEXT
    CHECK (return_mechanism IS NULL OR return_mechanism IN (
      'BUYER_SHIPS_VIA_COURIER', 'CLIENT_PICKS_UP'
    )),
  reason TEXT,
  buyer_complaint TEXT,
  pickup_courier_user_id BIGINT,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  evidence JSONB,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_returns_order FOREIGN KEY (order_id, client_id)
    REFERENCES ruta.orders(id, client_id),
  CONSTRAINT fk_returns_buyer FOREIGN KEY (buyer_id, client_id)
    REFERENCES ruta.users(id, client_id),
  CONSTRAINT fk_returns_courier FOREIGN KEY (pickup_courier_user_id, client_id)
    REFERENCES ruta.users(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 19. DISPUTAS
-- ============================================================================

CREATE TABLE ruta.disputes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  buyer_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'DISPUTED'
    CHECK (status IN ('DISPUTED', 'DISPUTE_RESOLVED')),
  reason TEXT,
  resolution TEXT,
  resolution_action TEXT
    CHECK (resolution_action IS NULL OR resolution_action IN (
      'NONE', 'APPROVE_RETURN', 'APPROVE_REFUND_NO_RETURN'
    )),
  resolved_by_user_id BIGINT,
  resolved_at TIMESTAMPTZ,
  evidence JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_disputes_order FOREIGN KEY (order_id, client_id)
    REFERENCES ruta.orders(id, client_id),
  CONSTRAINT fk_disputes_buyer FOREIGN KEY (buyer_id, client_id)
    REFERENCES ruta.users(id, client_id),
  CONSTRAINT fk_disputes_resolver FOREIGN KEY (resolved_by_user_id, client_id)
    REFERENCES ruta.users(id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 20. WEBHOOKS
-- ============================================================================
-- NOTA: webhook_subscriptions NO se particiona (volumen bajo, pocos endpoints
-- por cliente). En cambio, webhook_deliveries SÍ se particiona porque es el
-- log de cada intento de entrega (alto volumen). La PK de webhook_subscriptions
-- es simple (id) para que el FK desde webhook_deliveries por solo (id) funcione.
-- La limpieza al offboarding se hace con DELETE explícito en
-- delete_client_permanently().
-- ============================================================================

-- Suscripciones de webhooks salientes (RUTA → Cliente)
CREATE TABLE ruta.webhook_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  url TEXT NOT NULL,
  events TEXT[] NOT NULL,
  signing_secret TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'INACTIVE')),
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id),
  CONSTRAINT fk_ws_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id)
);


-- Entregas de webhooks salientes (log de cada intento)
CREATE TABLE ruta.webhook_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  subscription_id BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  event_id TEXT NOT NULL,
  payload JSONB NOT NULL,
  attempt_number INT NOT NULL DEFAULT 1,
  response_status INT,
  response_body TEXT,
  delivered_at TIMESTAMPTZ,
  next_retry_at TIMESTAMPTZ,
  failed_permanently BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  CONSTRAINT fk_wd_subscription FOREIGN KEY (subscription_id)
    REFERENCES ruta.webhook_subscriptions(id)
) PARTITION BY LIST (client_id);


-- Webhooks entrantes (proveedor de pago → RUTA)
CREATE TABLE ruta.external_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL,
  payment_provider_id BIGINT NOT NULL,
  provider_event_id TEXT NOT NULL,
  payload JSONB NOT NULL,
  signature_valid BOOLEAN,
  processed_at TIMESTAMPTZ,
  processing_result TEXT,
  related_order_id BIGINT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (payment_provider_id, provider_event_id)
);


-- ============================================================================
-- SECCIÓN 21. AUDITORÍA (append-only)
-- ============================================================================

CREATE TABLE ruta.audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,

  -- Quién
  actor_user_id BIGINT,
  actor_api_key_id BIGINT,
  actor_type TEXT,
  actor_role TEXT,
  acting_via_control_view BOOLEAN NOT NULL DEFAULT FALSE,
  impersonator_user_id BIGINT,
  control_view_session_id BIGINT,

  -- Qué
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id BIGINT,

  -- Cómo
  ip_address INET,
  user_agent TEXT,
  metadata JSONB,
  result TEXT NOT NULL
    CHECK (result IN ('SUCCESS', 'FAILURE', 'DENIED')),

  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 22. IDEMPOTENCY KEYS
-- ============================================================================

CREATE TABLE ruta.idempotency_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  actor_id BIGINT NOT NULL,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('USER', 'API_KEY')),
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  response_status INT NOT NULL,
  response_body JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),

  PRIMARY KEY (id, client_id),
  UNIQUE (client_id, actor_type, actor_id, idempotency_key)
) PARTITION BY LIST (client_id);


-- ============================================================================
-- SECCIÓN 23. CATÁLOGO DE ESTADOS (referencia para UI/reportes)
-- ============================================================================

CREATE TABLE ruta.state_catalog (
  state_dimension TEXT NOT NULL,
  state_value TEXT NOT NULL,
  description TEXT,
  is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INT,
  applies_to_client_type TEXT NOT NULL DEFAULT 'BOTH'
    CHECK (applies_to_client_type IN ('BOTH', 'FULL_ONLY', 'API_ONLY')),
  PRIMARY KEY (state_dimension, state_value)
);

COMMENT ON TABLE ruta.state_catalog IS
  'Catálogo de estados de todas las dimensiones. No es fuente de verdad
  (los CHECK en cada tabla lo son), pero sirve para UI y reportes.';


-- ============================================================================
-- SECCIÓN 24. ÍNDICES
-- ============================================================================

-- clients
CREATE INDEX idx_clients_status ON ruta.clients (status);
CREATE INDEX idx_clients_type ON ruta.clients (client_type);

-- users
CREATE INDEX idx_users_client_email ON ruta.users (client_id, email);
CREATE INDEX idx_users_client_type_status
  ON ruta.users (client_id, user_type, status);
CREATE INDEX idx_users_client_external_buyer
  ON ruta.users (client_id, external_buyer_id) WHERE external_buyer_id IS NOT NULL;
CREATE INDEX idx_users_client_document
  ON ruta.users (client_id, document_type, document_number)
  WHERE document_number IS NOT NULL;

-- sessions
CREATE INDEX idx_sessions_user_active
  ON ruta.sessions (client_id, user_id) WHERE revoked_at IS NULL;
CREATE INDEX idx_sessions_refresh_hash
  ON ruta.sessions (refresh_token_hash) WHERE revoked_at IS NULL;
CREATE INDEX idx_sessions_expires
  ON ruta.sessions (expires_at) WHERE revoked_at IS NULL;

-- client_api_keys
CREATE INDEX idx_cak_key_id_active
  ON ruta.client_api_keys (key_id) WHERE revoked_at IS NULL;

-- client_payment_providers
CREATE INDEX idx_cpp_client_status
  ON ruta.client_payment_providers (client_id, status);
CREATE INDEX idx_cpp_webhook_path
  ON ruta.client_payment_providers (webhook_ingress_path)
  WHERE webhook_ingress_path IS NOT NULL;

-- products
CREATE INDEX idx_products_client_status
  ON ruta.products (client_id, status);
CREATE INDEX idx_products_client_category
  ON ruta.products (client_id, category_id) WHERE category_id IS NOT NULL;

-- orders
CREATE INDEX idx_orders_client_status
  ON ruta.orders (client_id, order_status);
CREATE INDEX idx_orders_client_buyer_status
  ON ruta.orders (client_id, buyer_id, order_status);
CREATE INDEX idx_orders_client_courier
  ON ruta.orders (client_id, courier_user_id)
  WHERE courier_user_id IS NOT NULL;
CREATE INDEX idx_orders_client_created_desc
  ON ruta.orders (client_id, created_at DESC);
CREATE INDEX idx_orders_client_payment_status
  ON ruta.orders (client_id, payment_status);
CREATE INDEX idx_orders_client_origin
  ON ruta.orders (client_id, order_origin);
CREATE INDEX idx_orders_client_refund_status
  ON ruta.orders (client_id, refund_status)
  WHERE refund_status != 'REFUND_NOT_REQUIRED';
CREATE INDEX idx_orders_client_delivery_type
  ON ruta.orders (client_id, delivery_type);

-- order_items
CREATE INDEX idx_oi_client_order
  ON ruta.order_items (client_id, order_id);

-- order_state_history
CREATE INDEX idx_osh_client_order_occurred
  ON ruta.order_state_history (client_id, order_id, occurred_at DESC);
CREATE INDEX idx_osh_client_dimension
  ON ruta.order_state_history (client_id, state_dimension, occurred_at DESC);

-- payments
CREATE INDEX idx_payments_client_order
  ON ruta.payments (client_id, order_id);
CREATE INDEX idx_payments_client_status
  ON ruta.payments (client_id, status);
CREATE INDEX idx_payments_client_courier
  ON ruta.payments (client_id, collected_by_courier_user_id)
  WHERE collected_by_courier_user_id IS NOT NULL;
CREATE INDEX idx_payments_client_reconciled
  ON ruta.payments (client_id, reconciled_with_client);
CREATE INDEX idx_payments_external_txn
  ON ruta.payments (client_id, external_transaction_id)
  WHERE external_transaction_id IS NOT NULL;

-- refunds
CREATE INDEX idx_refunds_client_order
  ON ruta.refunds (client_id, order_id);
CREATE INDEX idx_refunds_client_status
  ON ruta.refunds (client_id, status);

-- returns
CREATE INDEX idx_returns_client_order
  ON ruta.returns (client_id, order_id);
CREATE INDEX idx_returns_client_status
  ON ruta.returns (client_id, status);
CREATE INDEX idx_returns_client_buyer
  ON ruta.returns (client_id, buyer_id);

-- disputes
CREATE INDEX idx_disputes_client_order
  ON ruta.disputes (client_id, order_id);
CREATE INDEX idx_disputes_client_status
  ON ruta.disputes (client_id, status);

-- audit_events
CREATE INDEX idx_audit_client_occurred_desc
  ON ruta.audit_events (client_id, occurred_at DESC);
CREATE INDEX idx_audit_client_actor
  ON ruta.audit_events (client_id, actor_user_id, occurred_at DESC)
  WHERE actor_user_id IS NOT NULL;
CREATE INDEX idx_audit_client_entity
  ON ruta.audit_events (client_id, entity_type, entity_id);
CREATE INDEX idx_audit_control_view
  ON ruta.audit_events (client_id, control_view_session_id)
  WHERE acting_via_control_view = TRUE;

-- webhooks
CREATE INDEX idx_wd_client_subscription
  ON ruta.webhook_deliveries (client_id, subscription_id);
CREATE INDEX idx_wd_client_next_retry
  ON ruta.webhook_deliveries (client_id, next_retry_at)
  WHERE delivered_at IS NULL AND failed_permanently = FALSE;

CREATE INDEX idx_ewe_processed
  ON ruta.external_webhook_events (processed_at)
  WHERE processed_at IS NULL;

-- idempotency_keys
CREATE INDEX idx_idem_expires
  ON ruta.idempotency_keys (expires_at);

-- recurrence_templates
CREATE INDEX idx_rt_client_status
  ON ruta.recurrence_templates (client_id, recurrence_status);
CREATE INDEX idx_rt_next_generation
  ON ruta.recurrence_templates (next_generation_at)
  WHERE recurrence_status = 'RECURRENCE_ACTIVE';


-- ============================================================================
-- SECCIÓN 25. TRIGGERS DE updated_at
-- ============================================================================

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON ruta.users
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_buyer_profiles_updated_at BEFORE UPDATE ON ruta.buyer_profiles
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_courier_profiles_updated_at BEFORE UPDATE ON ruta.courier_profiles
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_cpp_updated_at BEFORE UPDATE ON ruta.client_payment_providers
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_pickup_points_updated_at BEFORE UPDATE ON ruta.pickup_points
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_pc_updated_at BEFORE UPDATE ON ruta.product_categories
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON ruta.products
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_rt_updated_at BEFORE UPDATE ON ruta.recurrence_templates
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON ruta.orders
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_payments_updated_at BEFORE UPDATE ON ruta.payments
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_refunds_updated_at BEFORE UPDATE ON ruta.refunds
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_returns_updated_at BEFORE UPDATE ON ruta.returns
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_disputes_updated_at BEFORE UPDATE ON ruta.disputes
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();
CREATE TRIGGER trg_ws_updated_at BEFORE UPDATE ON ruta.webhook_subscriptions
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();


-- ============================================================================
-- SECCIÓN 26. FUNCIÓN Y TRIGGER PARA AUTO-CREACIÓN DE PARTICIONES
-- ============================================================================

CREATE OR REPLACE FUNCTION ruta.create_client_partitions(p_client_id BIGINT)
RETURNS VOID AS $$
DECLARE
  partitioned_tables TEXT[] := ARRAY[
    'users', 'buyer_profiles', 'courier_profiles',
    'client_payment_providers',
    'pickup_points', 'product_categories', 'products',
    'recurrence_templates', 'orders', 'order_items',
    'order_state_history', 'payments', 'refunds',
    'returns', 'disputes', 'webhook_deliveries',
    'audit_events', 'idempotency_keys',
    'client_parameters', 'operator_permissions'
  ];
  t TEXT;
BEGIN
  FOREACH t IN ARRAY partitioned_tables LOOP
    BEGIN
      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS ruta.%I_p%s PARTITION OF ruta.%I FOR VALUES IN (%L)',
        t, p_client_id, t, p_client_id
      );
    EXCEPTION
      WHEN undefined_table THEN
        -- La tabla padre aún no existe. Esto solo debe ocurrir durante el
        -- bootstrap del schema, cuando se inserta el Cliente plataforma (id=0)
        -- antes de que client_parameters y operator_permissions hayan sido
        -- creadas (ver SECCIÓN 33B). Las particiones para esas tablas se
        -- crean manualmente al final de la SECCIÓN 33B. Para cualquier otro
        -- Cliente nuevo todas las tablas ya existen y esta rama no se ejecuta.
        NULL;
    END;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION ruta.create_client_partitions IS
  'Crea todas las particiones para un client_id dado. Se ejecuta
  automáticamente al insertar en clients vía trigger. Resiliente a tablas
  padre faltantes (solo durante bootstrap del cliente plataforma).';


CREATE OR REPLACE FUNCTION ruta.trg_auto_create_partitions()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM ruta.create_client_partitions(NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_clients_auto_partitions
AFTER INSERT ON ruta.clients
FOR EACH ROW
EXECUTE FUNCTION ruta.trg_auto_create_partitions();


-- ============================================================================
-- SECCIÓN 27. FUNCIÓN Y TRIGGER PARA HISTORIAL DE ESTADOS DE PEDIDOS
-- ============================================================================

CREATE OR REPLACE FUNCTION ruta.trg_log_order_state_change()
RETURNS TRIGGER AS $$
BEGIN
  -- order_status
  IF NEW.order_status IS DISTINCT FROM OLD.order_status THEN
    INSERT INTO ruta.order_state_history (
      client_id, order_id, state_dimension, previous_value, new_value
    ) VALUES (
      NEW.client_id, NEW.id, 'order_status', OLD.order_status, NEW.order_status
    );
  END IF;

  -- payment_status
  IF NEW.payment_status IS DISTINCT FROM OLD.payment_status THEN
    INSERT INTO ruta.order_state_history (
      client_id, order_id, state_dimension, previous_value, new_value
    ) VALUES (
      NEW.client_id, NEW.id, 'payment_status', OLD.payment_status, NEW.payment_status
    );
  END IF;

  -- refund_status
  IF NEW.refund_status IS DISTINCT FROM OLD.refund_status THEN
    INSERT INTO ruta.order_state_history (
      client_id, order_id, state_dimension, previous_value, new_value
    ) VALUES (
      NEW.client_id, NEW.id, 'refund_status', OLD.refund_status, NEW.refund_status
    );
  END IF;

  -- return_status
  IF NEW.return_status IS DISTINCT FROM OLD.return_status THEN
    INSERT INTO ruta.order_state_history (
      client_id, order_id, state_dimension, previous_value, new_value
    ) VALUES (
      NEW.client_id, NEW.id, 'return_status', OLD.return_status, NEW.return_status
    );
  END IF;

  -- dispute_status
  IF NEW.dispute_status IS DISTINCT FROM OLD.dispute_status THEN
    INSERT INTO ruta.order_state_history (
      client_id, order_id, state_dimension, previous_value, new_value
    ) VALUES (
      NEW.client_id, NEW.id, 'dispute_status', OLD.dispute_status, NEW.dispute_status
    );
  END IF;

  -- Incrementar version
  NEW.version = OLD.version + 1;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_orders_log_state
BEFORE UPDATE ON ruta.orders
FOR EACH ROW
EXECUTE FUNCTION ruta.trg_log_order_state_change();


-- ============================================================================
-- SECCIÓN 28. PROCEDIMIENTOS DE OPERACIÓN
-- ============================================================================

-- Cancelar pedidos activos cuando se desactiva un Cliente
CREATE OR REPLACE FUNCTION ruta.cancel_client_active_orders(
  p_client_id BIGINT,
  p_admin_user_id BIGINT
)
RETURNS INT AS $$
DECLARE
  cancelled_count INT;
BEGIN
  WITH cancelled AS (
    UPDATE ruta.orders
    SET order_status = 'CANCELLED_BY_ADMIN',
        closure_reason = 'CLIENT_DEACTIVATED',
        closed_at = NOW(),
        refund_status = CASE
          WHEN payment_status = 'PAID' AND order_origin != 'API_LOGISTICS'
            THEN 'REFUND_PENDING'
          ELSE refund_status
        END
    WHERE client_id = p_client_id
      AND order_status NOT IN ('CLOSED', 'COMPLETED_SUCCESSFULLY')
    RETURNING 1
  )
  SELECT COUNT(*) INTO cancelled_count FROM cancelled;

  INSERT INTO ruta.audit_events (
    client_id, actor_user_id, actor_type, action, entity_type, entity_id, result, metadata
  ) VALUES (
    p_client_id, p_admin_user_id, 'ADMIN_RUTA',
    'CLIENT_DEACTIVATION_CASCADE_CANCEL', 'client', p_client_id, 'SUCCESS',
    jsonb_build_object('cancelled_count', cancelled_count)
  );

  RETURN cancelled_count;
END;
$$ LANGUAGE plpgsql;


-- Eliminar definitivamente datos de un Cliente (hard delete)
CREATE OR REPLACE FUNCTION ruta.purge_client_data(
  p_client_id BIGINT,
  p_admin_user_id BIGINT
)
RETURNS VOID AS $$
DECLARE
  client_status TEXT;
  partitioned_tables TEXT[] := ARRAY[
    'users', 'buyer_profiles', 'courier_profiles',
    'client_payment_providers',
    'pickup_points', 'product_categories', 'products',
    'recurrence_templates', 'orders', 'order_items',
    'order_state_history', 'payments', 'refunds',
    'returns', 'disputes', 'webhook_deliveries',
    'idempotency_keys',
    'client_parameters', 'operator_permissions'
  ];
  t TEXT;
BEGIN
  -- Validar que el Cliente esté INACTIVE
  SELECT status INTO client_status FROM ruta.clients WHERE id = p_client_id;
  IF client_status IS NULL THEN
    RAISE EXCEPTION 'Cliente % no existe', p_client_id;
  END IF;
  IF client_status != 'INACTIVE' THEN
    RAISE EXCEPTION 'Cliente % debe estar INACTIVE para ser eliminado', p_client_id;
  END IF;
  IF p_client_id = 0 THEN
    RAISE EXCEPTION 'No se puede eliminar el cliente plataforma (id=0)';
  END IF;

  -- Auditar la acción (en audit_events del Cliente plataforma)
  INSERT INTO ruta.audit_events (
    client_id, actor_user_id, actor_type, action, entity_type, entity_id, result, metadata
  ) VALUES (
    0, p_admin_user_id, 'ADMIN_RUTA',
    'CLIENT_PERMANENT_DELETION', 'client', p_client_id, 'SUCCESS',
    jsonb_build_object('purged_at', NOW())
  );

  -- Drop de todas las particiones del Cliente
  FOREACH t IN ARRAY partitioned_tables LOOP
    EXECUTE format('DROP TABLE IF EXISTS ruta.%I_p%s CASCADE', t, p_client_id);
  END LOOP;

  -- Tablas multi-tenant NO particionadas (ver SECCIONES 8 y 20). Se borran
  -- explícitamente. Orden importante: webhook_subscriptions después del DROP
  -- de la partición de webhook_deliveries (que tiene FK hacia ella).
  DELETE FROM ruta.client_api_keys      WHERE client_id = p_client_id;
  DELETE FROM ruta.webhook_subscriptions WHERE client_id = p_client_id;

  -- NOTA: audit_events del Cliente eliminado se conservan en su partición
  -- por requerimiento legal. NO se elimina la partición de audit_events.

  -- Eliminar el registro del cliente
  DELETE FROM ruta.clients WHERE id = p_client_id;
END;
$$ LANGUAGE plpgsql;


-- Limpieza de idempotency_keys expirados (job de mantenimiento)
CREATE OR REPLACE FUNCTION ruta.cleanup_expired_idempotency_keys()
RETURNS INT AS $$
DECLARE
  deleted_count INT;
BEGIN
  WITH deleted AS (
    DELETE FROM ruta.idempotency_keys
    WHERE expires_at < NOW()
    RETURNING 1
  )
  SELECT COUNT(*) INTO deleted_count FROM deleted;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;


-- Limpieza de sesiones expiradas o revocadas hace más de 30 días
CREATE OR REPLACE FUNCTION ruta.cleanup_expired_sessions()
RETURNS INT AS $$
DECLARE
  deleted_count INT;
BEGIN
  WITH deleted AS (
    DELETE FROM ruta.sessions
    WHERE (revoked_at IS NOT NULL AND revoked_at < NOW() - INTERVAL '30 days')
       OR (expires_at < NOW() - INTERVAL '30 days')
    RETURNING 1
  )
  SELECT COUNT(*) INTO deleted_count FROM deleted;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;


-- Revocar todas las sesiones activas de un usuario
CREATE OR REPLACE FUNCTION ruta.revoke_user_sessions(
  p_client_id BIGINT,
  p_user_id BIGINT,
  p_reason TEXT
)
RETURNS INT AS $$
DECLARE
  revoked_count INT;
BEGIN
  WITH revoked AS (
    UPDATE ruta.sessions
    SET revoked_at = NOW(),
        revocation_reason = p_reason
    WHERE client_id = p_client_id
      AND user_id = p_user_id
      AND revoked_at IS NULL
    RETURNING 1
  )
  SELECT COUNT(*) INTO revoked_count FROM revoked;
  RETURN revoked_count;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- SECCIÓN 29. APPEND-ONLY: revocar UPDATE/DELETE en tablas inmutables
-- ============================================================================

REVOKE UPDATE, DELETE ON ruta.audit_events FROM ruta_app;
REVOKE UPDATE, DELETE ON ruta.order_state_history FROM ruta_app;
REVOKE UPDATE, DELETE ON ruta.external_webhook_events FROM ruta_app;
REVOKE UPDATE, DELETE ON ruta.webhook_deliveries FROM ruta_app;


-- ============================================================================
-- SECCIÓN 30. ROW LEVEL SECURITY
-- ============================================================================

-- Habilitar RLS en todas las tablas operativas
ALTER TABLE ruta.users                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.buyer_profiles            ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.courier_profiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.client_api_keys           ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.client_payment_providers  ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.pickup_points             ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.product_categories        ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.products                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.recurrence_templates      ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.orders                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.order_items               ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.order_state_history       ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.payments                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.refunds                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.returns                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.disputes                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.webhook_deliveries        ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.audit_events              ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.idempotency_keys          ENABLE ROW LEVEL SECURITY;


-- Política general: aislamiento por client_id del contexto
-- El backend debe ejecutar: SET LOCAL app.current_client_id = '<n>';
-- Y: SET LOCAL app.current_user_role = '<rol>';

CREATE POLICY tenant_isolation ON ruta.users FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.buyer_profiles FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.courier_profiles FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.client_api_keys FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.client_payment_providers FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.pickup_points FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.product_categories FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.products FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.recurrence_templates FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.orders FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.order_items FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.order_state_history FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.payments FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.refunds FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.returns FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.disputes FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.webhook_deliveries FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.audit_events FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

CREATE POLICY tenant_isolation ON ruta.idempotency_keys FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');


-- ============================================================================
-- SECCIÓN 31. GRANTS
-- ============================================================================

GRANT USAGE ON SCHEMA ruta TO ruta_app, ruta_jobs, ruta_readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ruta TO ruta_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ruta TO ruta_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ruta TO ruta_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ruta TO ruta_jobs;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ruta TO ruta_jobs;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ruta TO ruta_jobs;

GRANT SELECT ON ALL TABLES IN SCHEMA ruta TO ruta_readonly;

-- Reaplicar revocación de UPDATE/DELETE en tablas append-only
REVOKE UPDATE, DELETE ON ruta.audit_events FROM ruta_app;
REVOKE UPDATE, DELETE ON ruta.order_state_history FROM ruta_app;
REVOKE UPDATE, DELETE ON ruta.external_webhook_events FROM ruta_app;
REVOKE UPDATE, DELETE ON ruta.webhook_deliveries FROM ruta_app;

-- Defaults para futuros objetos
ALTER DEFAULT PRIVILEGES IN SCHEMA ruta
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ruta_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ruta
  GRANT USAGE, SELECT ON SEQUENCES TO ruta_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ruta
  GRANT SELECT ON TABLES TO ruta_readonly;


-- ============================================================================
-- SECCIÓN 32. CLIENTE PLATAFORMA Y PARTICIONES INICIALES
-- ============================================================================

-- Insertar el cliente especial id = 0 (RUTA Platform)
-- Esto dispara automáticamente la creación de particiones para client_id = 0
INSERT INTO ruta.clients (
  id, business_code, slug, name, description, client_type, frontend_mode, status
) VALUES (
  0, 'RUTA-PLATFORM', 'ruta-platform', 'RUTA Platform',
  'Cliente especial que representa la plataforma. Aloja a los usuarios ADMIN_RUTA.',
  'FULL', 'NATIVE_RUTA', 'ACTIVE'
);


-- ============================================================================
-- SECCIÓN 33. CATÁLOGO DE ESTADOS (DATOS DE REFERENCIA)
-- ============================================================================

-- order_status
INSERT INTO ruta.state_catalog (state_dimension, state_value, description, is_terminal, display_order, applies_to_client_type) VALUES
('order_status', 'DRAFT', 'Pedido iniciado, sin confirmar', FALSE, 10, 'FULL_ONLY'),
('order_status', 'PENDING_CONFIRM', 'Pendiente de confirmación de entrega y pago', FALSE, 20, 'FULL_ONLY'),
('order_status', 'ORDER_SUBMITTED', 'Pedido enviado al sistema', FALSE, 30, 'FULL_ONLY'),
('order_status', 'EXPIRED', 'Pedido vencido sin confirmar', FALSE, 40, 'FULL_ONLY'),
('order_status', 'ORDER_VALIDATING', 'En validación operativa', FALSE, 50, 'FULL_ONLY'),
('order_status', 'MANUAL_REVIEW', 'En revisión humana', FALSE, 60, 'FULL_ONLY'),
('order_status', 'VALIDATION_APPROVED', 'Validación aprobada', FALSE, 70, 'FULL_ONLY'),
('order_status', 'VALIDATION_REJECTED', 'Validación rechazada', FALSE, 80, 'FULL_ONLY'),
('order_status', 'SELLER_CONFIRMED', 'Aceptado por el vendedor', FALSE, 90, 'FULL_ONLY'),
('order_status', 'PREPARING', 'En preparación', FALSE, 100, 'BOTH'),
('order_status', 'AWAITING_COURIER_ASSIGNMENT', 'Esperando asignación de repartidor', FALSE, 110, 'BOTH'),
('order_status', 'COURIER_ASSIGNED', 'Repartidor asignado', FALSE, 120, 'BOTH'),
('order_status', 'READY_TO_SHIP', 'Listo para despacho', FALSE, 130, 'BOTH'),
('order_status', 'READY_FOR_PICKUP', 'Listo para recogida', FALSE, 140, 'BOTH'),
('order_status', 'SHIPMENT_HOLD', 'Despacho retenido', FALSE, 150, 'BOTH'),
('order_status', 'SHIPPED', 'Despachado', FALSE, 160, 'BOTH'),
('order_status', 'IN_TRANSIT', 'En tránsito', FALSE, 170, 'BOTH'),
('order_status', 'ON_HOLD', 'Tránsito retenido', FALSE, 180, 'BOTH'),
('order_status', 'OUT_FOR_DELIVERY', 'En reparto final', FALSE, 190, 'BOTH'),
('order_status', 'ARRIVED_AT_CUSTOMER', 'Llegada al comprador', FALSE, 200, 'BOTH'),
('order_status', 'DELIVERY_ATTEMPTED', 'Entrega intentada', FALSE, 210, 'BOTH'),
('order_status', 'DELIVERY_RESCHEDULED', 'Entrega reprogramada', FALSE, 220, 'BOTH'),
('order_status', 'LOST_IN_TRANSIT', 'Perdido en tránsito', TRUE, 230, 'BOTH'),
('order_status', 'AT_PICKUP_POINT', 'Disponible en punto físico', FALSE, 240, 'BOTH'),
('order_status', 'CUSTOMER_ARRIVED_AT_PICKUP_POINT', 'Comprador llegó a punto', FALSE, 250, 'BOTH'),
('order_status', 'IDENTITY_VALIDATED', 'Identidad validada', FALSE, 260, 'BOTH'),
('order_status', 'PICKUP_AUTH_FAILED', 'Identidad no válida', FALSE, 270, 'BOTH'),
('order_status', 'PICKUP_POINT_ISSUE', 'Problema en punto físico', FALSE, 280, 'BOTH'),
('order_status', 'PICKUP_EXPIRED', 'Plazo de pickup vencido', TRUE, 290, 'BOTH'),
('order_status', 'PICKUP_CANCELLED_BY_CUSTOMER', 'Comprador no retira', TRUE, 300, 'BOTH'),
('order_status', 'PICKED_UP', 'Recogido por comprador', FALSE, 310, 'BOTH'),
('order_status', 'PAYMENT_COLLECTION_PENDING', 'Cobro electrónico pendiente', FALSE, 320, 'BOTH'),
('order_status', 'PAYMENT_COLLECTED_ELECTRONIC', 'Cobro electrónico exitoso', FALSE, 330, 'BOTH'),
('order_status', 'PAYMENT_COLLECTED_CASH', 'Cobro en efectivo exitoso', FALSE, 340, 'BOTH'),
('order_status', 'CASH_COLLECTION_PENDING', 'Cobro en efectivo pendiente', FALSE, 350, 'BOTH'),
('order_status', 'CASH_PAYMENT_REJECTED', 'Comprador no pagó efectivo', FALSE, 360, 'BOTH'),
('order_status', 'CANCELLED_BY_CUSTOMER', 'Cancelado por comprador', TRUE, 370, 'BOTH'),
('order_status', 'CANCELLED_BY_SELLER', 'Cancelado por vendedor', TRUE, 380, 'FULL_ONLY'),
('order_status', 'CANCELLED_BY_SYSTEM', 'Cancelado por sistema', TRUE, 390, 'FULL_ONLY'),
('order_status', 'CANCELLED_BY_ADMIN', 'Cancelado por administrador', TRUE, 400, 'BOTH'),
('order_status', 'CANCELLED_NO_PAYMENT', 'Cancelado sin pago', TRUE, 410, 'BOTH'),
('order_status', 'CUSTOMER_CANCEL_REQUEST', 'Solicitud de cancelación post-despacho', FALSE, 420, 'BOTH'),
('order_status', 'CANCEL_REQUEST_APPROVED', 'Solicitud de cancelación aprobada', FALSE, 430, 'BOTH'),
('order_status', 'CANCEL_REQUEST_REJECTED', 'Solicitud de cancelación rechazada', FALSE, 440, 'BOTH'),
('order_status', 'RETURN_TO_ORIGIN', 'Retorno al origen logístico', FALSE, 450, 'BOTH'),
('order_status', 'RETURN_TO_ORIGIN_RECEIVED', 'Recibido en origen', FALSE, 460, 'BOTH'),
('order_status', 'LOST_IN_RETURN', 'Perdido en retorno', TRUE, 470, 'BOTH'),
('order_status', 'DELIVERED', 'Entregado', FALSE, 480, 'BOTH'),
('order_status', 'DELIVERY_DISPUTED', 'Entrega disputada', FALSE, 490, 'FULL_ONLY'),
('order_status', 'CONFIRMED_BY_CUSTOMER', 'Confirmado por comprador', FALSE, 500, 'FULL_ONLY'),
('order_status', 'CONFIRMED_BY_SYSTEM', 'Confirmado automáticamente', FALSE, 510, 'BOTH'),
('order_status', 'COMPLETED_SUCCESSFULLY', 'Completado exitosamente', FALSE, 520, 'BOTH'),
('order_status', 'CLOSED', 'Cerrado (estado final)', TRUE, 999, 'BOTH');

-- payment_status
INSERT INTO ruta.state_catalog (state_dimension, state_value, description, is_terminal, display_order, applies_to_client_type) VALUES
('payment_status', 'PAYMENT_NOT_STARTED', 'Pago no iniciado', FALSE, 10, 'BOTH'),
('payment_status', 'PENDING_ONLINE_PAYMENT', 'Pendiente pago online', FALSE, 20, 'FULL_ONLY'),
('payment_status', 'PAYMENT_PROCESSING', 'Pasarela procesando', FALSE, 30, 'FULL_ONLY'),
('payment_status', 'PAID', 'Pagado', FALSE, 40, 'BOTH'),
('payment_status', 'PAYMENT_FAILED_RETRYABLE', 'Pago fallido reintentable', FALSE, 50, 'FULL_ONLY'),
('payment_status', 'PAYMENT_REJECTED_FINAL', 'Pago rechazado definitivamente', TRUE, 60, 'FULL_ONLY'),
('payment_status', 'PENDING_COLLECTION', 'Pendiente de cobro en entrega', FALSE, 70, 'BOTH'),
('payment_status', 'COLLECTION_PROCESSING', 'Cobro electrónico en proceso', FALSE, 80, 'BOTH'),
('payment_status', 'PAYMENT_COLLECTED', 'Cobrado', FALSE, 90, 'BOTH'),
('payment_status', 'PAYMENT_COLLECTION_FAILED', 'Cobro fallido reintentable', FALSE, 100, 'BOTH'),
('payment_status', 'PAYMENT_NOT_COLLECTED', 'No se logró cobrar', TRUE, 110, 'BOTH');

-- refund_status
INSERT INTO ruta.state_catalog (state_dimension, state_value, description, is_terminal, display_order, applies_to_client_type) VALUES
('refund_status', 'REFUND_NOT_REQUIRED', 'No requiere reembolso', FALSE, 10, 'FULL_ONLY'),
('refund_status', 'REFUND_PENDING', 'Reembolso pendiente', FALSE, 20, 'FULL_ONLY'),
('refund_status', 'REFUND_PROCESSING', 'Reembolso en proceso', FALSE, 30, 'FULL_ONLY'),
('refund_status', 'REFUND_PROVIDER_REQUESTED', 'Solicitado al proveedor', FALSE, 40, 'FULL_ONLY'),
('refund_status', 'REFUNDED', 'Reembolsado totalmente', TRUE, 50, 'FULL_ONLY'),
('refund_status', 'PARTIALLY_REFUNDED', 'Reembolso parcial', TRUE, 60, 'FULL_ONLY'),
('refund_status', 'REFUND_FAILED', 'Reembolso fallido', FALSE, 70, 'FULL_ONLY');

-- return_status
INSERT INTO ruta.state_catalog (state_dimension, state_value, description, is_terminal, display_order, applies_to_client_type) VALUES
('return_status', 'RETURN_REQUESTED', 'Devolución solicitada', FALSE, 10, 'FULL_ONLY'),
('return_status', 'RETURN_UNDER_REVIEW', 'En revisión por el Cliente', FALSE, 20, 'FULL_ONLY'),
('return_status', 'RETURN_APPROVED', 'Devolución aprobada', FALSE, 30, 'FULL_ONLY'),
('return_status', 'RETURN_REJECTED', 'Devolución rechazada', TRUE, 40, 'FULL_ONLY'),
('return_status', 'RETURN_CANCELLED', 'Devolución cancelada', TRUE, 50, 'FULL_ONLY'),
('return_status', 'CUSTOMER_RETURN_IN_TRANSIT', 'Producto en retorno (courier)', FALSE, 60, 'FULL_ONLY'),
('return_status', 'CUSTOMER_RETURN_EXPIRED', 'Plazo de retorno vencido', TRUE, 70, 'FULL_ONLY'),
('return_status', 'CUSTOMER_RETURN_RECEIVED', 'Producto recibido', TRUE, 80, 'FULL_ONLY'),
('return_status', 'CUSTOMER_RETURN_LOST', 'Producto perdido en retorno', TRUE, 90, 'FULL_ONLY'),
('return_status', 'PICKUP_SCHEDULED', 'Recogida programada', FALSE, 100, 'FULL_ONLY'),
('return_status', 'PICKUP_OUT_FOR_COLLECTION', 'Repartidor en camino a recoger', FALSE, 110, 'FULL_ONLY'),
('return_status', 'PICKUP_COLLECTED', 'Producto recogido por repartidor', FALSE, 120, 'FULL_ONLY'),
('return_status', 'PICKUP_FAILED', 'Falló la recogida', FALSE, 130, 'FULL_ONLY');

-- dispute_status
INSERT INTO ruta.state_catalog (state_dimension, state_value, description, is_terminal, display_order, applies_to_client_type) VALUES
('dispute_status', 'DISPUTED', 'Disputa abierta', FALSE, 10, 'FULL_ONLY'),
('dispute_status', 'DISPUTE_RESOLVED', 'Disputa resuelta', TRUE, 20, 'FULL_ONLY');

-- recurrence_status
INSERT INTO ruta.state_catalog (state_dimension, state_value, description, is_terminal, display_order, applies_to_client_type) VALUES
('recurrence_status', 'RECURRENCE_ACTIVE', 'Plantilla activa', FALSE, 10, 'FULL_ONLY'),
('recurrence_status', 'RECURRENCE_PAUSED', 'Plantilla pausada', FALSE, 20, 'FULL_ONLY'),
('recurrence_status', 'RECURRENCE_CANCELLED', 'Plantilla cancelada', TRUE, 30, 'FULL_ONLY');

-- closure_reason
INSERT INTO ruta.state_catalog (state_dimension, state_value, description, is_terminal, display_order, applies_to_client_type) VALUES
('closure_reason', 'COMPLETED_SUCCESSFULLY', 'Pedido entregado y pago resuelto', TRUE, 10, 'BOTH'),
('closure_reason', 'CANCELLED_BY_CUSTOMER', 'Cancelado por el comprador', TRUE, 20, 'BOTH'),
('closure_reason', 'CANCELLED_BY_SELLER', 'Cancelado por el vendedor', TRUE, 30, 'FULL_ONLY'),
('closure_reason', 'CANCELLED_BY_SYSTEM', 'Cancelado por sistema', TRUE, 40, 'FULL_ONLY'),
('closure_reason', 'CANCELLED_BY_ADMIN', 'Cancelado por administrador', TRUE, 50, 'BOTH'),
('closure_reason', 'CANCELLED_NO_PAYMENT', 'Comprador no pagó al entregar', TRUE, 60, 'BOTH'),
('closure_reason', 'PAYMENT_TIMEOUT', 'Pago online no completado a tiempo', TRUE, 70, 'FULL_ONLY'),
('closure_reason', 'PAYMENT_REJECTED', 'Pago online rechazado', TRUE, 80, 'FULL_ONLY'),
('closure_reason', 'VALIDATION_REJECTED', 'Rechazado por validación', TRUE, 90, 'FULL_ONLY'),
('closure_reason', 'DELIVERY_FAILED', 'Entrega fallida definitiva', TRUE, 100, 'BOTH'),
('closure_reason', 'PICKUP_EXPIRED', 'Plazo de retiro vencido', TRUE, 110, 'BOTH'),
('closure_reason', 'LOST_IN_TRANSIT', 'Perdido en tránsito', TRUE, 120, 'BOTH'),
('closure_reason', 'LOST_IN_RETURN', 'Perdido en retorno', TRUE, 130, 'BOTH'),
('closure_reason', 'EXPIRED', 'Pedido vencido sin confirmar', TRUE, 140, 'FULL_ONLY'),
('closure_reason', 'CLIENT_DEACTIVATED', 'Cliente desactivado', TRUE, 150, 'BOTH');


-- ============================================================================
-- SECCIÓN 33B. TABLAS DE PARÁMETROS Y PERMISOS DE OPERADOR
-- ============================================================================

-- Parámetros de negocio configurables por Cliente
-- (con override sobre los defaults globales de client_id = 0)
CREATE TABLE ruta.client_parameters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  parameter_key TEXT NOT NULL,
  parameter_value TEXT NOT NULL,
  value_type TEXT NOT NULL
    CHECK (value_type IN ('INTEGER', 'DECIMAL', 'STRING', 'BOOLEAN', 'JSON')),
  description TEXT,
  is_overrideable_by_client BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id, client_id),
  UNIQUE (client_id, parameter_key),
  CONSTRAINT fk_cparam_client FOREIGN KEY (client_id) REFERENCES ruta.clients(id)
) PARTITION BY LIST (client_id);

COMMENT ON TABLE ruta.client_parameters IS
  'Parámetros operativos. Valores globales viven en client_id=0;
  cualquier Cliente puede override individualmente si
  is_overrideable_by_client = TRUE.';


-- Permisos granulares para OPERATOR_CLIENT
CREATE TABLE ruta.operator_permissions (
  operator_user_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  permission_key TEXT NOT NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  granted_by_user_id BIGINT NOT NULL,

  PRIMARY KEY (operator_user_id, client_id, permission_key),
  CONSTRAINT fk_op_user FOREIGN KEY (operator_user_id, client_id)
    REFERENCES ruta.users(id, client_id),
  CONSTRAINT fk_op_granter FOREIGN KEY (granted_by_user_id, client_id)
    REFERENCES ruta.users(id, client_id)
) PARTITION BY LIST (client_id);

COMMENT ON TABLE ruta.operator_permissions IS
  'Permisos granulares por OPERATOR_CLIENT. ADMIN_CLIENT y
  ADMIN_RUTA tienen todos los permisos implícitamente; esta tabla
  solo registra los explícitos otorgados a OPERATOR_CLIENT.';


-- Índices
CREATE INDEX idx_cparam_client_key ON ruta.client_parameters (client_id, parameter_key);
CREATE INDEX idx_op_perm_user ON ruta.operator_permissions (client_id, operator_user_id);

-- Triggers updated_at
CREATE TRIGGER trg_cparam_updated_at BEFORE UPDATE ON ruta.client_parameters
  FOR EACH ROW EXECUTE FUNCTION ruta.trg_set_updated_at();

-- RLS
ALTER TABLE ruta.client_parameters    ENABLE ROW LEVEL SECURITY;
ALTER TABLE ruta.operator_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON ruta.client_parameters FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA'
         OR client_id = 0);  -- global params readable by anyone

CREATE POLICY tenant_isolation ON ruta.operator_permissions FOR ALL
  USING (client_id = current_setting('app.current_client_id', TRUE)::BIGINT
         OR current_setting('app.current_user_role', TRUE) = 'ADMIN_RUTA');

-- Crear particiones para client_id = 0 (la inserción del Cliente plataforma
-- ya disparó el trigger, pero estas tablas se crearon DESPUÉS — hay que crear
-- sus particiones manualmente para client_id = 0)
CREATE TABLE IF NOT EXISTS ruta.client_parameters_p0
  PARTITION OF ruta.client_parameters FOR VALUES IN (0);
CREATE TABLE IF NOT EXISTS ruta.operator_permissions_p0
  PARTITION OF ruta.operator_permissions FOR VALUES IN (0);


-- ============================================================================
-- SECCIÓN 33C. PARÁMETROS GLOBALES POR DEFECTO (client_id = 0)
-- ============================================================================

-- Plazos de pedido (Flujo 1, Cliente Full)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'order.draft_expiration_minutes', '1440', 'INTEGER', 'Tiempo máximo en DRAFT antes de auto-cancelarse', TRUE),
(0, 'order.pending_confirm_timeout_minutes', '60', 'INTEGER', 'Tiempo máximo en PENDING_CONFIRM antes de EXPIRED', TRUE),
(0, 'order.pending_online_payment_timeout_minutes', '15', 'INTEGER', 'Tiempo máximo para completar pago online', TRUE),
(0, 'order.validation_max_duration_minutes', '5', 'INTEGER', 'Tiempo máximo en ORDER_VALIDATING', TRUE),
(0, 'order.manual_review_sla_hours', '24', 'INTEGER', 'SLA para resolver MANUAL_REVIEW', TRUE),
(0, 'order.seller_confirmation_timeout_hours', '4', 'INTEGER', 'Tiempo para aceptación del vendedor', TRUE),
(0, 'order.pickup_expiration_hours', '24', 'INTEGER', 'Tiempo máximo en READY_FOR_PICKUP antes de EXPIRED', TRUE);

-- Plazos de despacho (Flujo 2)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'ship.courier_assignment_timeout_minutes', '30', 'INTEGER', 'Timeout en AWAITING_COURIER_ASSIGNMENT', TRUE),
(0, 'ship.preparation_max_hours', '24', 'INTEGER', 'Máximo en PREPARING antes de alerta', TRUE),
(0, 'ship.delivery_attempt_max_retries', '3', 'INTEGER', 'Intentos de entrega antes de retorno', TRUE),
(0, 'ship.delivery_attempt_retry_hours', '24', 'INTEGER', 'Tiempo entre intentos de entrega', TRUE),
(0, 'ship.in_transit_max_hours', '72', 'INTEGER', 'Máximo en IN_TRANSIT antes de alerta', TRUE),
(0, 'ship.cancel_request_review_hours', '2', 'INTEGER', 'Tiempo para revisar CUSTOMER_CANCEL_REQUEST', TRUE);

-- Plazos de pickup (Flujo 3)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'pickup.expiration_hours', '48', 'INTEGER', 'Máximo en AT_PICKUP_POINT antes de PICKUP_EXPIRED', TRUE),
(0, 'pickup.notification_reminder_hours', '24', 'INTEGER', 'Recordatorio antes de expiración', TRUE);

-- Confirmación final
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'closure.auto_confirm_delivered_hours', '72', 'INTEGER', 'Tiempo en DELIVERED antes de CONFIRMED_BY_SYSTEM', TRUE),
(0, 'closure.dispute_window_hours', '72', 'INTEGER', 'Ventana para abrir disputa post-DELIVERED', TRUE);

-- Reembolsos (Flujo 4, solo Cliente Full)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'refund.processing_sla_business_days', '5', 'INTEGER', 'SLA del Cliente para ejecutar reembolso', TRUE),
(0, 'refund.provider_response_timeout_hours', '72', 'INTEGER', 'Timeout de respuesta del proveedor', TRUE);

-- Devoluciones (Flujo 7, solo Cliente Full)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'return.review_sla_hours', '72', 'INTEGER', 'Tiempo del Cliente para aprobar devolución', TRUE),
(0, 'return.review_auto_action', 'APPROVE', 'STRING', 'Acción automática sin respuesta', TRUE),
(0, 'return.buyer_ships_deadline_days', '15', 'INTEGER', 'Plazo para que el Comprador despache', TRUE),
(0, 'return.pickup_schedule_max_attempts', '2', 'INTEGER', 'Intentos máximos de recogida CLIENT_PICKS_UP', TRUE);

-- Recurrencia (Flujo 5)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'recurrence.generation_lookahead_hours', '24', 'INTEGER', 'Anticipación de generación de pedido recurrente', TRUE),
(0, 'recurrence.max_skipped_cycles', '3', 'INTEGER', 'Ciclos fallidos antes de pausar', TRUE);

-- Sesiones y autenticación
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'auth.jwt_lifetime_admin_ruta_minutes', '15', 'INTEGER', 'Duración JWT para ADMIN_RUTA', FALSE),
(0, 'auth.jwt_lifetime_admin_client_minutes', '15', 'INTEGER', 'Duración JWT para ADMIN_CLIENT', FALSE),
(0, 'auth.jwt_lifetime_operator_client_minutes', '15', 'INTEGER', 'Duración JWT para OPERATOR_CLIENT', FALSE),
(0, 'auth.jwt_lifetime_buyer_minutes', '15', 'INTEGER', 'Duración JWT para BUYER', FALSE),
(0, 'auth.jwt_lifetime_courier_minutes', '30', 'INTEGER', 'Duración JWT para COURIER', FALSE),
(0, 'auth.refresh_token_lifetime_admin_days', '30', 'INTEGER', 'Refresh para admin roles', FALSE),
(0, 'auth.refresh_token_lifetime_buyer_days', '90', 'INTEGER', 'Refresh para BUYER', FALSE),
(0, 'auth.refresh_token_lifetime_courier_days', '30', 'INTEGER', 'Refresh para COURIER', FALSE),
(0, 'auth.max_failed_login_attempts', '5', 'INTEGER', 'Intentos fallidos antes de bloqueo', FALSE),
(0, 'auth.lockout_duration_minutes', '30', 'INTEGER', 'Tiempo de bloqueo tras superar intentos', FALSE),
(0, 'auth.password_min_length', '10', 'INTEGER', 'Longitud mínima de contraseña', FALSE),
(0, 'auth.password_require_complexity', 'true', 'BOOLEAN', 'Requerir complejidad en contraseña', FALSE);

-- Vista de Control
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'control_view.master_password_rotation_days', '90', 'INTEGER', 'Rotación recomendada (no forzada en v1)', FALSE),
(0, 'control_view.notify_admin_client', 'false', 'BOOLEAN', 'Notificar al ADMIN_CLIENT cuando entran a Vista de Control', FALSE);

-- Webhooks (no overrideable)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'webhook.max_retries', '6', 'INTEGER', 'Reintentos máximos antes de permanent failure', FALSE),
(0, 'webhook.retry_intervals_minutes', '[1,5,15,60,360,1440]', 'JSON', 'Intervalos de reintento', FALSE),
(0, 'webhook.delivery_timeout_seconds', '10', 'INTEGER', 'Timeout HTTP por intento', FALSE),
(0, 'webhook.signing_algorithm', 'HMAC-SHA256', 'STRING', 'Algoritmo de firma', FALSE);

-- Idempotencia y sesiones (no overrideable)
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'idempotency.key_ttl_hours', '24', 'INTEGER', 'TTL de idempotency keys', FALSE),
(0, 'session.cleanup_after_revoked_days', '30', 'INTEGER', 'Días tras revocación antes de purgar', FALSE),
(0, 'session.cleanup_after_expired_days', '30', 'INTEGER', 'Días tras expiración antes de purgar', FALSE);

-- Cobranza contra entrega
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'collection.electronic_retry_max_attempts', '3', 'INTEGER', 'Reintentos de cobro electrónico', TRUE),
(0, 'collection.cash_change_max_amount', '100000', 'DECIMAL', 'Devuelta máxima en efectivo (alerta)', TRUE),
(0, 'collection.evidence_required', 'true', 'BOOLEAN', 'Evidencia obligatoria en cobro', TRUE);

-- Storage
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'storage.max_file_size_mb', '10', 'INTEGER', 'Tamaño máximo de archivo', FALSE),
(0, 'storage.allowed_image_formats', '["jpg","jpeg","png","webp"]', 'JSON', 'Formatos permitidos', FALSE),
(0, 'storage.evidence_retention_days', '730', 'INTEGER', 'Retención de evidencias en días', TRUE),
(0, 'storage.product_image_max_count', '5', 'INTEGER', 'Imágenes máximas por producto', TRUE);

-- Catálogo
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'catalog.bulk_import_max_rows', '5000', 'INTEGER', 'Filas máximas por carga Excel', TRUE),
(0, 'catalog.bulk_import_concurrent_max', '1', 'INTEGER', 'Imports simultáneos por Cliente', FALSE),
(0, 'catalog.default_currency', 'COP', 'STRING', 'Moneda por defecto', TRUE);

-- Mapa
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'map.provider', 'OSM', 'STRING', 'Proveedor de mapa', FALSE),
(0, 'map.tile_cache_hours', '24', 'INTEGER', 'Cache de tiles en frontend', FALSE),
(0, 'map.default_center_lat', '4.7110', 'DECIMAL', 'Centro por defecto (Bogotá)', TRUE),
(0, 'map.default_center_lng', '-74.0721', 'DECIMAL', 'Centro por defecto (Bogotá)', TRUE);

-- Notificaciones
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'notifications.email_enabled', 'true', 'BOOLEAN', 'Email habilitado', TRUE),
(0, 'notifications.sms_enabled', 'false', 'BOOLEAN', 'SMS habilitado', TRUE),
(0, 'notifications.push_enabled', 'false', 'BOOLEAN', 'Push notifications habilitado', TRUE);

-- Límites operativos
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'limits.max_active_recurrences_per_buyer', '10', 'INTEGER', 'Plantillas recurrentes activas por Comprador', TRUE),
(0, 'limits.max_buyer_addresses', '10', 'INTEGER', 'Direcciones guardadas por Comprador', TRUE),
(0, 'limits.max_api_keys_per_client', '5', 'INTEGER', 'API keys activas por Cliente API', TRUE),
(0, 'limits.max_pickup_points_per_client', '50', 'INTEGER', 'Puntos físicos por Cliente', TRUE),
(0, 'limits.max_couriers_per_client', '200', 'INTEGER', 'Repartidores activos por Cliente', TRUE);

-- Rate limiting
INSERT INTO ruta.client_parameters (client_id, parameter_key, parameter_value, value_type, description, is_overrideable_by_client) VALUES
(0, 'ratelimit.api_requests_per_minute_per_apikey', '300', 'INTEGER', 'Rate limit por API key', FALSE),
(0, 'ratelimit.public_requests_per_minute_per_ip', '60', 'INTEGER', 'Rate limit endpoints públicos', FALSE),
(0, 'ratelimit.auth_attempts_per_minute_per_ip', '5', 'INTEGER', 'Rate limit intentos de login', FALSE);


-- ============================================================================
-- SECCIÓN 34. VERIFICACIONES FINALES
-- ============================================================================

-- Verificar que el cliente plataforma existe y tiene sus particiones
DO $$
DECLARE
  partition_count INT;
BEGIN
  SELECT COUNT(*) INTO partition_count
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'ruta'
    AND c.relname LIKE '%_p0'
    AND c.relkind = 'r';

  IF partition_count < 20 THEN
    RAISE WARNING 'Solo se crearon % particiones para el cliente plataforma. Esperadas: al menos 20.', partition_count;
  END IF;
END
$$;

COMMIT;

-- ============================================================================
-- FIN DEL MODELO DE DATOS
-- ============================================================================
-- Para crear un nuevo Cliente operativo:
--   INSERT INTO ruta.clients (business_code, slug, name, client_type, frontend_mode)
--   VALUES ('CLI-0001', 'restaurante-el-prado', 'Restaurante El Prado', 'FULL', 'NATIVE_RUTA');
--
-- Las particiones se crean automáticamente vía trigger.
--
-- Para crear el primer ADMIN_RUTA tras instalar:
--   INSERT INTO ruta.users (client_id, user_type, email, password_hash, auth_mode, full_name, status)
--   VALUES (0, 'ADMIN_RUTA', 'admin@ruta.com', '<argon2id hash>', 'PASSWORD', 'Admin Principal', 'ACTIVE');
-- ============================================================================
